// ==========================================
// 📚 src/data.js — 資料庫 (請勿在 App.jsx 中硬編碼資料)
// ==========================================

const KANJI_DICT = {
  // --- 數字、時刻、量詞特例 (解決濁音與促音變化，長詞優先匹配) ---
  "1つ": "ひとつ", "一つ": "ひとつ", "2つ": "ふたつ", "二つ": "ふたつ", "3つ": "みっつ", "三つ": "みっつ",
  "300": "さんびゃく", "三百": "さんびゃく", "600": "ろっぴゃく", "六百": "ろっぴゃく", "800": "はっぴゃく", "八百": "はっぴゃく",
  "3000": "さんぜん", "三千": "さんぜん", "8000": "はっせん", "八千": "はっせん", "10000": "いちまん", "一万": "いちまん",
  "4時": "よじ", "四時": "よじ", "5時": "ごじ", "7時": "しちじ", "七時": "しちじ", "9時": "くじ", "九時": "くじ", 
  "10時": "じゅうじ", "11時": "じゅういちじ", "12時": "じゅうにじ", "1時": "いちじ", "何時": "なんじ",
  "1分": "いっぷん", "一分": "いっぷん", "3分": "さんぷん", "三分": "さんぷん", "4分": "よんぷん", "四分": "よんぷん",
  "6分": "ろっぷん", "六分": "ろっぷん", "8分": "はっぷん", "八分": "はっぷん", "10分": "じゅっぷん", "十分": "じゅっぷん", "何分": "なんぷん",
  "1日": "ついたち", "一日": "ついたち", "2日": "ふつか", "二日": "ふつか", "3日": "みっか", "三日": "みっか",
  "4日": "よっか", "四日": "よっか", "5日": "いつか", "五日": "いつか", "6日": "むいか", "六日": "むいか",
  "7日": "なのか", "七日": "なのか", "8日": "ようか", "八日": "ようか", "9日": "ここのか", "九日": "ここのか",
  "10日": "とおか", "十日": "とおか", "14日": "じゅうよっか", "十四日": "じゅうよっか", "20日": "はつか", "二十日": "はつか",
  "24日": "にじゅうよっか", "二十四日": "にじゅうよっか", "何日": "なんにち",
  "1人": "ひとり", "一人": "ひとり", "2人": "ふたり", "二人": "ふたり", "3人": "さんにん", "4人": "よにん", "四人": "よにん", "何人": "なんにん",
  "1個": "いっこ", "一個": "いっこ", "6個": "ろっこ", "六個": "ろっこ", "8個": "はっこ", "八個": "はっこ", "10個": "じゅっこ", "十個": "じゅっこ", "何個": "なんこ",
  "1本": "いっぽん", "一本": "いっぽん", "2本": "にほん", "3本": "さんぼん", "三本": "さんぼん", "6本": "ろっぽん", "六本": "ろっぽん",
  "8本": "はっぽん", "八本": "はっぽん", "10本": "じゅっぽん", "十本": "じゅっぽん", "何本": "なんぼん",
  "1冊": "いっさつ", "一冊": "いっさつ", "3冊": "さんさつ", "8冊": "はっさつ", "八冊": "はっさつ", "10冊": "じゅっさつ", "十冊": "じゅっさつ", "何冊": "なんさつ",
  "1回": "いっかい", "一回": "いっかい", "6回": "ろっかい", "六回": "ろっかい", "8回": "はっかい", "八回": "はっかい", "10回": "じゅっかい", "十回": "じゅっかい", "何回": "なんかい",
  "1階": "いっかい", "一階": "いっかい", "3階": "さんがい", "三階": "さんがい", "6階": "ろっかい", "六階": "ろっかい", "8階": "はっかい", "八階": "はっかい", "10階": "じゅっかい", "十階": "じゅっかい", "何階": "なんがい",
  "7月": "しちがつ", "8月": "はちがつ", "12時間": "じゅうにじかん", "2000年": "にせんねん", "二十歳": "はたち",

  // --- 姓氏 ---
  "陳": "ちん", "林": "りん", "黄": "こう", "洪": "こう", "張": "ちょう", "李": "り", "王": "おう", "呉": "ご", "劉": "りゅう", "蔡": "さい", "楊": "よう", "葉": "よう",
  "許": "きょ", "鄭": "てい", "謝": "しゃ", "郭": "かく", "邱": "きゅう", "曾": "そ", "廖": "りょう", "頼": "らい", "徐": "じょ", "周": "しゅう",

  // --- 家人稱謂 ---
  "祖父": "そふ", "祖母": "そぼ", "お爺さん": "おじいさん", "お婆さん": "おばあさん", "父": "ちち", "母": "はは", "兄": "あに", "姉": "あね", "弟さん": "おとうとさん",
  "妹さん": "いもうとさん", "息子": "むすこ", "娘": "むすめ", "お嬢さん": "おじょうさん", "弟": "おとうと", "妹": "いもうと",

  // --- 特殊發音或複合詞 (長詞優先比對) ---
  "学生食堂": "がくせいしょくどう", "電話番号": "でんわばんごう", "電子辞書": "でんしじしょ", "日本料理": "にほんりょうり", "会社員": "かいしゃいん", "公務員": "こうむいん", "送別会": "そうべつかい",
  "自転車": "じてんしゃ", "洗濯機": "せんたくき", "お母さん": "おかあさん", "お父さん": "おとうさん", "お姉さん": "おねえさん", "お兄さん": "おにいさん", "初めまして": "はじめまして", "教科書": "きょうかしょ",
  "日曜日": "にちようび", "月曜日": "げつようび", "火曜日": "かようび", "水曜日": "すいようび", "木曜日": "もくようび", "金曜日": "きんようび", "土曜日": "どようび", "何曜日": "なんようび",
  "誕生日": "たんじょうび", "大晦日": "おおみそか", "夏休み": "なつやすみ", "冬休み": "ふゆやすみ", "昼休み": "ひるやすみ", "図書館": "としょかん", "飛行機": "ひこうき", "昼ご飯": "ひるごはん",
  "朝ご飯": "あさごはん", "晩ご飯": "ばんごはん", "親子丼": "おやこどん", "お風呂": "おふろ", "学生証": "がくせいしょう", "映画館": "えいがかん", "郵便局": "ゆうびんきょく", "冷蔵庫": "れいぞうこ",
  "男の子": "おとこのこ", "女の子": "おんなのこ", "男の人": "おとこのひと", "女の人": "おんなのひと", "買い物": "かいもの", "食べ物": "たべもの", "お土産": "おみやげ", "お菓子": "おかし", "お酒": "おさけ",
  "私達": "わたしたち", "時計": "とけい", "交番": "こうばん", "病院": "びょういん", "本棚": "ほんだな", "牛乳": "ぎゅうにゅう", "銀行": "ぎんこう", "果物": "くだもの", "漫画": "まんが", "今度": "こんど",
  "新聞": "しんぶん", "音楽": "おんがく", "弁当": "べんとう", "一緒": "いっしょ", "素敵": "すてき", "午前": "ごぜん", "午後": "ごご", "週末": "しゅうまつ", "風邪": "かぜ", "電気": "でんき", "写真": "しゃしん",
  "試験": "しけん", "東京": "とうきょう", "沖縄": "おきなわ", "香港": "ほんこん", "電車": "でんしゃ", "石鹸": "せっけん", "時間": "じかん", "自分": "じぶん", "荷物": "にもつ", "天丼": "てんどん",
  "駅前": "えきまえ", "名前": "なまえ", "住所": "じゅうしょ", "本屋": "ほんや", "出口": "でぐち", "一度": "いちど", "芸術": "げいじゅつ", "眼鏡": "めがね", "最近": "さいきん", "昔": "むかし",
  "仲良し": "なかよし", "親友": "しんゆう", "洋服": "ようふく", "大声": "おおごえ", "他人": "たにん", "悪口": "わるくち", "部長": "ぶちょう", "芝生": "しばふ", "心得": "こころえ", "電源": "でんげん",
  "共用": "きょうよう", "玄関": "げんかん", "生活": "せいかつ", "試着": "しちゃく", "説明": "せつめい", "相談": "そうだん", "質問": "しつもん", "遅刻": "ちこく", "掃除": "そうじ", "紅茶": "こうちゃ",
  "林檎": "りんご", "空港": "くうこう", "先生": "せんせい", "学生": "がくせい", "生徒": "せいと", "鈴木": "すずき", "友達": "ともだち", "何時": "なんじ", "何分": "なんぷん", "何ですか": "なんですか",
  "今日": "きょう", "明日": "あした", "昨日": "きのう", "今朝": "けさ", "夕日": "ゆうひ", "休みの日": "やすみのひ", "一昨日": "おととい", "先週": "せんしゅう", "今週": "こんしゅう", "来週": "らいしゅう", "来月": "らいげつ",
  "今年": "ことし", "来年": "らいねん", "高校": "こうこう", "仕事": "しごと", "宿題": "しゅくだい", "旅行": "りょこう", "料理": "りょうり", "勉強": "べんきょう", "全然": "ぜんぜん", "向かい側": "むかいがわ",
  
  // --- 解決動詞多重讀音的衝突 (先比對帶尾音的動詞) ---
  "出かけ": "でかけ", "出し": "だし", "出す": "だす", "下ろし": "おろし", "下ろす": "おろす",
  "行きます": "いきます", "行って": "いって", "来ます": "きます", "来る": "くる", "来ない": "こない",

  // --- 兩字名詞與形容詞 ---
  "専攻": "せんこう", "授業": "じゅぎょう", "彼女": "かのじょ", "鉛筆": "えんぴつ", "帽子": "ぼうし", "辞書": "じしょ", "雑誌": "ざっし", "椅子": "いす", "会社": "かいしゃ", "店員": "てんいん",
  "教室": "きょうしつ", "部屋": "へや", "安全": "あんぜん", "綺麗": "きれい", "上手": "じょうず", "親切": "しんせつ", "新鮮": "しんせん", "得意": "とくい", "苦手": "にがて", "下手": "へた",
  "元気": "げんき", "子供": "こども", "納豆": "なっとう", "日本": "にほん", "台湾": "たいわん", "中国": "ちゅうごく", "韓国": "かんこく", "英語": "えいご", "大変": "たいへん", "真面目": "まじめ",
  "有名": "ゆうめい", "簡単": "かんたん", "天気": "てんき", "黄色": "きいろ",

  // --- 單字、詞根、動詞/形容詞字幹 (最後比對) ---
  "青": "あお", "赤": "あか", "黒": "くろ", "白": "しろ", "黄": "き", "新": "あたら", "古": "ふる", "良": "よ", "悪": "わる", "大": "おお", "小": "ちい",
  "重": "おも", "軽": "かる", "高": "たか", "安": "やす", "美味": "おい", "面白": "おもしろ", "狭": "せま", "広": "ひろ", "静": "しず", "好": "す", "賑": "にぎ", "明": "あか", "暗": "くら",
  "忙": "いそが", "楽": "たの", "暇": "ひま", "海": "うみ", "山": "やま", "寮": "りょう", "間": "あいだ", "上": "うえ", "下": "した", "前": "まえ", "後": "うし", "右": "みぎ", "左": "ひだり",
  "中": "なか", "外": "そと", "隣": "となり", "近": "ちか", "向": "む", "側": "がわ", "次": "つぎ", "所": "ところ", "暖": "あたた", "温": "あたた", "冷": "つめ", "甘": "あま", "痛": "いた", "長": "なが",
  "犬": "いぬ", "猫": "ねこ", "駅": "えき", "階": "かい", "家": "いえ", "裏": "うら", "庭": "にわ", "墓": "はか", "男": "おとこ", "女": "おんな", "子": "こ", "休": "やす", "店": "みせ", "手": "て",
  "夕": "ゆう", "夜": "よる", "風": "かぜ", "足": "あし", "頭": "あたま", "時": "じ", "年": "ねん", "今": "いま", "船": "ふね", "僕": "ぼく", "丼": "どんぶり", "元": "げん", "歯": "は", "顔": "かお",
  "番": "ばん", "頃": "ごろ", "歌": "うた", "道": "みち", "私": "わたし", "彼": "かれ", "傘": "かさ", "靴": "くつ", "車": "くるま", "町": "まち", "机": "つくえ", "本": "ほん", "人": "ひと", "物": "もの",
  "目": "め", "月": "がつ", "毎": "まい", "分": "ふん", "半": "はん", "誰": "だれ", "何": "なに",
  
  // 動詞字根
  "食": "た", "飲": "の", "見": "み", "聞": "き", "聴": "き", "書": "か", "読": "よ", "買": "か", "洗": "あら", "起": "お", "寝": "ね", "終": "お", "出": "で", "生": "う", "降": "ふ", "撮": "と",
  "消": "け", "忘": "わす", "欲": "ほ", "持": "も", "手伝": "てつだ", "止": "や", "作": "つく", "決": "き", "入": "はい", "座": "すわ", "乗": "の", "言": "い", "会": "あ", "教": "おし", "捨": "す",
  "閉": "し", "弾": "ひ", "泳": "およ", "住": "す", "履": "は", "穿": "は", "着": "き", "遊": "あそ", "話": "はな", "使": "つか", "吸": "す", "切": "き", "過": "すご", "帰": "かえ", "行": "い", "来": "き", "歩": "ある"
};

const KANJI_KEYS = Object.keys(KANJI_DICT).sort((a, b) => b.length - a.length);
const KANJI_REGEX = new RegExp(`(${KANJI_KEYS.join('|')})`, 'g');



const QUIZ_DATA = [
  // Chapter 1~10 Vocab
  { id: 301, chapter: '1', type: 'vocab', zh: '公司職員', ja: ['会社員'] },
  { id: 302, chapter: '1', type: 'vocab', zh: '公務員', ja: ['公務員'] },
  { id: 303, chapter: '1', type: 'katakana', zh: '美國', ja: ['アメリカ'] },
  { id: 304, chapter: '1', type: 'katakana', zh: '英國', ja: ['イギリス'] },
  { id: 305, chapter: '1', type: 'katakana', zh: '德國', ja: ['ドイツ'] },
  { id: 306, chapter: '1', type: 'vocab', zh: '主修', ja: ['専攻'] },
  { id: 307, chapter: '1', type: 'vocab', zh: '課程', ja: ['授業'] },
  { id: 308, chapter: '1', type: 'vocab', zh: '媽媽、母親(敬稱)', ja: ['お母さん'] },
  { id: 309, chapter: '1', type: 'vocab', zh: '爸爸、父親(敬稱)', ja: ['お父さん'] },
  { id: 310, chapter: '1', type: 'vocab', zh: '姊姊(敬稱)', ja: ['お姉さん'] },
  { id: 311, chapter: '1', type: 'vocab', zh: '她(第三人稱)', ja: ['彼女'] },
  { id: 312, chapter: '1', type: 'vocab', zh: '他(第三人稱)', ja: ['彼'] },
  { id: 316, chapter: '2', type: 'vocab', zh: '這個(近稱)', ja: ['これ'] },
  { id: 317, chapter: '2', type: 'vocab', zh: '那個(中稱)', ja: ['それ'] },
  { id: 318, chapter: '2', type: 'vocab', zh: '那個(遠稱)', ja: ['あれ'] },
  { id: 319, chapter: '2', type: 'vocab', zh: '哪一個', ja: ['どれ'] },
  { id: 320, chapter: '2', type: 'vocab', zh: '這~', ja: ['この'] },
  { id: 321, chapter: '2', type: 'vocab', zh: '那~(中稱)', ja: ['その'] },
  { id: 322, chapter: '2', type: 'vocab', zh: '那~(遠稱)', ja: ['あの'] },
  { id: 323, chapter: '2', type: 'vocab', zh: '哪~', ja: ['どの'] },
  { id: 324, chapter: '2', type: 'vocab', zh: '書', ja: ['本'] },
  { id: 325, chapter: '2', type: 'vocab', zh: '辭典', ja: ['辞書'] },
  { id: 326, chapter: '2', type: 'vocab', zh: '電子辭典', ja: ['電子辞書'] },
  { id: 327, chapter: '2', type: 'vocab', zh: '雜誌', ja: ['雑誌'] },
  { id: 328, chapter: '2', type: 'katakana', zh: '筆記本', ja: ['ノート'] },
  { id: 329, chapter: '2', type: 'vocab', zh: '教科書、課本', ja: ['教科書'] },
  { id: 330, chapter: '2', type: 'vocab', zh: '鉛筆', ja: ['鉛筆'] },
  { id: 331, chapter: '2', type: 'katakana', zh: '原子筆', ja: ['ボールペン'] },
  { id: 332, chapter: '2', type: 'vocab', zh: '傘', ja: ['傘'] },
  { id: 333, chapter: '2', type: 'vocab', zh: '包包、書包', ja: ['鞄'] },
  { id: 334, chapter: '2', type: 'vocab', zh: '椅子', ja: ['椅子'] },
  { id: 335, chapter: '2', type: 'vocab', zh: '窗戶', ja: ['窓'] },
  { id: 336, chapter: '2', type: 'vocab', zh: '茶', ja: ['お茶'] },
  { id: 337, chapter: '2', type: 'vocab', zh: '公司', ja: ['会社'] },
  { id: 338, chapter: '2', type: 'katakana', zh: '百貨公司', ja: ['デパート'] },
  { id: 339, chapter: '2', type: 'vocab', zh: '什麼', ja: ['何'] },
  { id: 340, chapter: '2', type: 'vocab', zh: '誰', ja: ['誰'] },
  { id: 3401, chapter: '2', type: 'vocab', zh: '那麼', ja: ['では', 'じゃ'] },
  { id: 341, chapter: '3', type: 'vocab', zh: '藍的、青的', ja: ['青い'] },
  { id: 342, chapter: '3', type: 'vocab', zh: '紅的', ja: ['赤い'] },
  { id: 343, chapter: '3', type: 'vocab', zh: '黑的', ja: ['黒い'] },
  { id: 344, chapter: '3', type: 'vocab', zh: '新的', ja: ['新しい'] },
  { id: 345, chapter: '3', type: 'vocab', zh: '舊的', ja: ['古い'] },
  { id: 346, chapter: '3', type: 'vocab', zh: '好的', ja: ['良い', 'いい', 'よい'] },
  { id: 347, chapter: '3', type: 'vocab', zh: '壞的', ja: ['悪い'] },
  { id: 348, chapter: '3', type: 'vocab', zh: '大的', ja: ['大きい'] },
  { id: 349, chapter: '3', type: 'vocab', zh: '小的', ja: ['小さい'] },
  { id: 350, chapter: '3', type: 'vocab', zh: '重的', ja: ['重い'] },
  { id: 351, chapter: '3', type: 'vocab', zh: '輕的', ja: ['軽い'] },
  { id: 352, chapter: '3', type: 'vocab', zh: '貴的、高的', ja: ['高い'] },
  { id: 353, chapter: '3', type: 'vocab', zh: '便宜的', ja: ['安い'] },
  { id: 354, chapter: '3', type: 'vocab', zh: '好吃的', ja: ['美味しい'] },
  { id: 355, chapter: '3', type: 'vocab', zh: '有趣的', ja: ['面白い'] },
  { id: 356, chapter: '3', type: 'vocab', zh: '狹窄的', ja: ['狭い'] },
  { id: 357, chapter: '3', type: 'vocab', zh: '寬廣的', ja: ['広い'] },
  { id: 358, chapter: '3', type: 'katakana', zh: '電視', ja: ['テレビ'] },
  { id: 359, chapter: '3', type: 'katakana', zh: '蛋糕', ja: ['ケーキ'] },
  { id: 360, chapter: '3', type: 'vocab', zh: '車子', ja: ['車'] },
  { id: 361, chapter: '3', type: 'vocab', zh: '店員', ja: ['店員'] },
  { id: 362, chapter: '3', type: 'vocab', zh: '顧客、客人', ja: ['客'] },
  { id: 363, chapter: '3', type: 'vocab', zh: '哥哥(敬稱)', ja: ['お兄さん'] },
  { id: 364, chapter: '3', type: 'vocab', zh: '教室', ja: ['教室'] },
  { id: 365, chapter: '3', type: 'vocab', zh: '房間', ja: ['部屋'] },
  { id: 366, chapter: '3', type: 'vocab', zh: '有一點、稍微', ja: ['ちょっと'] },
  { id: 367, chapter: '3', type: 'vocab', zh: '很、非常', ja: ['とても'] },
  { id: 368, chapter: '3', type: 'vocab', zh: '太~', ja: ['あまり'] },
  { id: 371, chapter: '4', type: 'vocab', zh: '安全的', ja: ['安全'] },
  { id: 372, chapter: '4', type: 'vocab', zh: '漂亮的、乾淨的', ja: ['綺麗', 'きれい'] },
  { id: 373, chapter: '4', type: 'vocab', zh: '安靜的', ja: ['静か'] },
  { id: 374, chapter: '4', type: 'vocab', zh: '很棒的、高明的', ja: ['上手'] },
  { id: 375, chapter: '4', type: 'vocab', zh: '親切的、和氣的', ja: ['親切'] },
  { id: 376, chapter: '4', type: 'vocab', zh: '新鮮的', ja: ['新鮮'] },
  { id: 377, chapter: '4', type: 'vocab', zh: '喜歡的', ja: ['好き'] },
  { id: 378, chapter: '4', type: 'vocab', zh: '拿手的', ja: ['得意'] },
  { id: 379, chapter: '4', type: 'vocab', zh: '不擅於、最怕、棘手', ja: ['苦手'] },
  { id: 380, chapter: '4', type: 'vocab', zh: '熱鬧的', ja: ['賑やか'] },
  { id: 381, chapter: '4', type: 'vocab', zh: '不熟練的、笨拙的', ja: ['下手'] },
  { id: 382, chapter: '4', type: 'vocab', zh: '有活力的', ja: ['元気'] },
  { id: 383, chapter: '4', type: 'vocab', zh: '星期天', ja: ['日曜日'] },
  { id: 384, chapter: '4', type: 'vocab', zh: '城鎮', ja: ['町'] },
  { id: 385, chapter: '4', type: 'vocab', zh: '人', ja: ['人'] },
  { id: 386, chapter: '4', type: 'vocab', zh: '小孩', ja: ['子供'] },
  { id: 387, chapter: '4', type: 'vocab', zh: '食物', ja: ['食べ物'] },
  { id: 388, chapter: '4', type: 'vocab', zh: '天婦羅、炸物', ja: ['天ぷら'] },
  { id: 389, chapter: '4', type: 'vocab', zh: '日式發酵黃豆食品', ja: ['納豆'] },
  { id: 390, chapter: '4', type: 'vocab', zh: '日本料理', ja: ['日本料理'] },
  { id: 391, chapter: '4', type: 'katakana', zh: '鋼琴', ja: ['ピアノ'] },
  { id: 392, chapter: '4', type: 'katakana', zh: '排球', ja: ['バレーボール'] },
  { id: 3921, chapter: '4', type: 'vocab', zh: '芒果剉冰', ja: ['マンゴーかき氷'] },
  { id: 393, chapter: '5', type: 'vocab', zh: '明亮的', ja: ['明るい'] },
  { id: 394, chapter: '5', type: 'vocab', zh: '黑的、暗的', ja: ['暗い'] },
  { id: 395, chapter: '5', type: 'vocab', zh: '忙碌的', ja: ['忙しい'] },
  { id: 396, chapter: '5', type: 'vocab', zh: '開心的、好玩的', ja: ['楽しい'] },
  { id: 397, chapter: '5', type: 'vocab', zh: '辛苦的', ja: ['大変'] },
  { id: 398, chapter: '5', type: 'vocab', zh: '空閒的', ja: ['暇'] },
  { id: 399, chapter: '5', type: 'vocab', zh: '認真的', ja: ['真面目'] },
  { id: 400, chapter: '5', type: 'vocab', zh: '有名的', ja: ['有名'] },
  { id: 401, chapter: '5', type: 'vocab', zh: '簡單的', ja: ['簡単'] },
  { id: 402, chapter: '5', type: 'vocab', zh: '海', ja: ['海'] },
  { id: 403, chapter: '5', type: 'vocab', zh: '山', ja: ['山'] },
  { id: 404, chapter: '5', type: 'vocab', zh: '夕陽', ja: ['夕日'] },
  { id: 405, chapter: '5', type: 'vocab', zh: '天氣', ja: ['天気'] },
  { id: 406, chapter: '5', type: 'vocab', zh: '昨天', ja: ['昨日'] },
  { id: 407, chapter: '5', type: 'vocab', zh: '上週、上星期', ja: ['先週'] },
  { id: 408, chapter: '5', type: 'vocab', zh: '高中', ja: ['高校'] },
  { id: 409, chapter: '5', type: 'vocab', zh: '宿舍', ja: ['寮'] },
  { id: 410, chapter: '5', type: 'vocab', zh: '工作', ja: ['仕事'] },
  { id: 411, chapter: '5', type: 'vocab', zh: '作業、習題', ja: ['宿題'] },
  { id: 412, chapter: '5', type: 'katakana', zh: '考試、測驗', ja: ['テスト'] },
  { id: 413, chapter: '5', type: 'katakana', zh: '派對、舞會', ja: ['パーティー'] },
  { id: 414, chapter: '5', type: 'katakana', zh: '個人電腦', ja: ['パソコン'] },
  { id: 415, chapter: '5', type: 'katakana', zh: '超市', ja: ['スーパー'] },
  { id: 416, chapter: '5', type: 'katakana', zh: '便利商店', ja: ['コンビニ'] },
  { id: 417, chapter: '5', type: 'katakana', zh: '三明治', ja: ['サンドイッチ'] },
  { id: 418, chapter: '5', type: 'vocab', zh: '旅行', ja: ['旅行'] },
  { id: 419, chapter: '5', type: 'vocab', zh: '料理', ja: ['料理'] },
  { id: 420, chapter: '5', type: 'vocab', zh: '土產、紀念品、伴手禮', ja: ['お土産'] },
  { id: 421, chapter: '5', type: 'vocab', zh: '課業、念書', ja: ['勉強'] },
  { id: 422, chapter: '5', type: 'vocab', zh: '完全不~(後接否定形)', ja: ['全然'] },
  { id: 423, chapter: '6', type: 'vocab', zh: '之間', ja: ['間'] },
  { id: 424, chapter: '6', type: 'vocab', zh: '上面、上方', ja: ['上'] },
  { id: 425, chapter: '6', type: 'vocab', zh: '下面、下方', ja: ['下'] },
  { id: 426, chapter: '6', type: 'vocab', zh: '前面、前方', ja: ['前'] },
  { id: 427, chapter: '6', type: 'vocab', zh: '後面、後方', ja: ['後ろ'] },
  { id: 428, chapter: '6', type: 'vocab', zh: '右邊、右方', ja: ['右'] },
  { id: 429, chapter: '6', type: 'vocab', zh: '左邊、左方', ja: ['左'] },
  { id: 430, chapter: '6', type: 'vocab', zh: '裡面', ja: ['中'] },
  { id: 431, chapter: '6', type: 'vocab', zh: '外面', ja: ['外'] },
  { id: 432, chapter: '6', type: 'vocab', zh: '旁邊、隔壁', ja: ['隣'] },
  { id: 433, chapter: '6', type: 'vocab', zh: '附近', ja: ['近く'] },
  { id: 434, chapter: '6', type: 'vocab', zh: '對面', ja: ['向かい側'] },
  { id: 435, chapter: '6', type: 'vocab', zh: '次一個、下一個', ja: ['次'] },
  { id: 436, chapter: '6', type: 'vocab', zh: '地方', ja: ['所'] },
  { id: 437, chapter: '6', type: 'vocab', zh: '哪裡', ja: ['どこ'] },
  { id: 438, chapter: '6', type: 'vocab', zh: '溫暖的、溫熱的', ja: ['暖かい', '温かい'] },
  { id: 439, chapter: '6', type: 'vocab', zh: '狗', ja: ['犬'] },
  { id: 440, chapter: '6', type: 'vocab', zh: '貓', ja: ['猫'] },
  { id: 441, chapter: '6', type: 'vocab', zh: '車站', ja: ['駅'] },
  { id: 442, chapter: '6', type: 'vocab', zh: '電影院', ja: ['映画館'] },
  { id: 443, chapter: '6', type: 'vocab', zh: '派出所', ja: ['交番'] },
  { id: 444, chapter: '6', type: 'vocab', zh: '醫院', ja: ['病院'] },
  { id: 445, chapter: '6', type: 'vocab', zh: '郵局', ja: ['郵便局'] },
  { id: 446, chapter: '6', type: 'katakana', zh: '公車站', ja: ['バス停'] },
  { id: 447, chapter: '6', type: 'vocab', zh: '冰箱', ja: ['冷蔵庫'] },
  { id: 448, chapter: '6', type: 'vocab', zh: '書架', ja: ['本棚'] },
  { id: 449, chapter: '6', type: 'vocab', zh: '暖桌', ja: ['こたつ'] },
  { id: 450, chapter: '6', type: 'vocab', zh: '牛奶', ja: ['牛乳'] },
  { id: 451, chapter: '6', type: 'katakana', zh: '橡皮擦', ja: ['消しゴム'] },
  { id: 452, chapter: '6', type: 'vocab', zh: '剪刀', ja: ['はさみ'] },
  { id: 453, chapter: '6', type: 'katakana', zh: '筆', ja: ['ペン'] },
  { id: 4531, chapter: '6', type: 'vocab', zh: '~樓', ja: ['階'] },
  { id: 454, chapter: '7', type: 'vocab', zh: '家、房子', ja: ['家'] },
  { id: 455, chapter: '7', type: 'vocab', zh: '內面、內情、反面', ja: ['裏'] },
  { id: 456, chapter: '7', type: 'vocab', zh: '院子、庭院', ja: ['庭'] },
  { id: 457, chapter: '7', type: 'vocab', zh: '銀行', ja: ['銀行'] },
  { id: 458, chapter: '7', type: 'katakana', zh: '餐廳', ja: ['レストラン'] },
  { id: 459, chapter: '7', type: 'katakana', zh: '餐桌', ja: ['テーブル'] },
  { id: 460, chapter: '7', type: 'katakana', zh: '床', ja: ['ベッド'] },
  { id: 461, chapter: '7', type: 'vocab', zh: '抽屜', ja: ['引出し'] },
  { id: 462, chapter: '7', type: 'vocab', zh: '墳墓', ja: ['墓'] },
  { id: 463, chapter: '7', type: 'vocab', zh: '東西、物品', ja: ['物'] },
  { id: 464, chapter: '7', type: 'vocab', zh: '水果', ja: ['果物'] },
  { id: 465, chapter: '7', type: 'katakana', zh: '香蕉', ja: ['バナナ'] },
  { id: 466, chapter: '7', type: 'vocab', zh: '漫畫', ja: ['漫画'] },
  { id: 467, chapter: '7', type: 'vocab', zh: '男孩', ja: ['男の子'] },
  { id: 468, chapter: '7', type: 'vocab', zh: '女孩', ja: ['女の子'] },
  { id: 469, chapter: '7', type: 'vocab', zh: '男人', ja: ['男の人'] },
  { id: 470, chapter: '7', type: 'vocab', zh: '女人', ja: ['女の人'] },
  { id: 471, chapter: '7', type: 'vocab', zh: '學生證', ja: ['学生証'] },
  { id: 472, chapter: '7', type: 'vocab', zh: '一個人', ja: ['1人', '一人'] },
  { id: 473, chapter: '7', type: 'vocab', zh: '兩個人', ja: ['2人', '二人'] },
  { id: 474, chapter: '7', type: 'vocab', zh: '很多', ja: ['たくさん'] },
  { id: 4744, chapter: '7', type: 'vocab', zh: '吵雜的', ja: ['うるさい'] },
  { id: 4745, chapter: '7', type: 'vocab', zh: '表示「不知道」時使用的感嘆詞', ja: ['さあ'] },
  { id: 4746, chapter: '7', type: 'vocab', zh: '錢包', ja: ['財布'] },
  { id: 475, chapter: '8', type: 'vocab', zh: '今天', ja: ['今日'] },
  { id: 476, chapter: '8', type: 'vocab', zh: '明天', ja: ['明日'] },
  { id: 477, chapter: '8', type: 'vocab', zh: '下回、距離現在最近的這次', ja: ['今度'] },
  { id: 478, chapter: '8', type: 'vocab', zh: '假日', ja: ['休みの日'] },
  { id: 479, chapter: '8', type: 'vocab', zh: '報紙', ja: ['新聞'] },
  { id: 480, chapter: '8', type: 'vocab', zh: '音樂', ja: ['音楽'] },
  { id: 481, chapter: '8', type: 'vocab', zh: '零食、點心', ja: ['お菓子'] },
  { id: 482, chapter: '8', type: 'vocab', zh: '飯', ja: ['ご飯'] },
  { id: 483, chapter: '8', type: 'vocab', zh: '便當', ja: ['弁当'] },
  { id: 484, chapter: '8', type: 'vocab', zh: '酒', ja: ['お酒'] },
  { id: 485, chapter: '8', type: 'vocab', zh: '商店', ja: ['店'] },
  { id: 486, chapter: '8', type: 'vocab', zh: '手', ja: ['手'] },
  { id: 487, chapter: '8', type: 'vocab', zh: '吃', ja: ['食べる', '食べます'] },
  { id: 488, chapter: '8', type: 'vocab', zh: '喝', ja: ['飲む', '飲みます'] },
  { id: 489, chapter: '8', type: 'vocab', zh: '看', ja: ['見る', '見ます'] },
  { id: 490, chapter: '8', type: 'vocab', zh: '聽、問', ja: ['聞く', '聴く', '聞きます'] },
  { id: 491, chapter: '8', type: 'vocab', zh: '寫', ja: ['書く', '書きます'] },
  { id: 492, chapter: '8', type: 'vocab', zh: '閱讀', ja: ['読む', '読みます'] },
  { id: 493, chapter: '8', type: 'vocab', zh: '買', ja: ['買う', '買います'] },
  { id: 494, chapter: '8', type: 'vocab', zh: '洗', ja: ['洗う', '洗います'] },
  { id: 495, chapter: '8', type: 'vocab', zh: '讀書、學習', ja: ['勉強する', '勉強します'] },
  { id: 496, chapter: '8', type: 'vocab', zh: '做菜、烹飪', ja: ['料理する', '料理します'] },
  { id: 497, chapter: '8', type: 'vocab', zh: '購物', ja: ['買い物する', '買い物します'] },
  { id: 498, chapter: '8', type: 'vocab', zh: '用餐', ja: ['食事する', '食事します'] },
  { id: 499, chapter: '8', type: 'vocab', zh: '運動', ja: ['運動する', '運動します'] },
  { id: 500, chapter: '8', type: 'vocab', zh: '一起', ja: ['一緒に'] },
  { id: 501, chapter: '8', type: 'vocab', zh: '總是', ja: ['いつも'] },
  { id: 502, chapter: '8', type: 'vocab', zh: '務必、無論如何', ja: ['ぜひ'] },
  { id: 503, chapter: '8', type: 'katakana', zh: '報告', ja: ['レポート'] },
  { id: 504, chapter: '8', type: 'vocab', zh: '極好的、漂亮的', ja: ['素敵'] },
  { id: 5041, chapter: '8', type: 'vocab', zh: '做', ja: ['する', 'します'] },
  { id: 505, chapter: '9', type: 'vocab', zh: '上午', ja: ['午前'] },
  { id: 506, chapter: '9', type: 'vocab', zh: '下午', ja: ['午後'] },
  { id: 507, chapter: '9', type: 'vocab', zh: '今天早上', ja: ['今朝'] },
  { id: 508, chapter: '9', type: 'vocab', zh: '昨晚', ja: ['夕べ'] },
  { id: 509, chapter: '9', type: 'vocab', zh: '前天', ja: ['一昨日'] },
  { id: 510, chapter: '9', type: 'vocab', zh: '晚上', ja: ['夜'] },
  { id: 511, chapter: '9', type: 'vocab', zh: '週末', ja: ['週末'] },
  { id: 512, chapter: '9', type: 'vocab', zh: '風', ja: ['風'] },
  { id: 513, chapter: '9', type: 'vocab', zh: '電燈、電', ja: ['電気'] },
  { id: 514, chapter: '9', type: 'vocab', zh: '照片', ja: ['写真'] },
  { id: 515, chapter: '9', type: 'vocab', zh: '腳、腿', ja: ['足'] },
  { id: 516, chapter: '9', type: 'vocab', zh: '頭部、頭腦', ja: ['頭'] },
  { id: 517, chapter: '9', type: 'vocab', zh: '長的', ja: ['長い'] },
  { id: 518, chapter: '9', type: 'vocab', zh: '疼痛的', ja: ['痛い'] },
  { id: 519, chapter: '9', type: 'vocab', zh: '起床、發生', ja: ['起きる', '起きます'] },
  { id: 520, chapter: '9', type: 'vocab', zh: '睡、就寢', ja: ['寝る', '寝ます'] },
  { id: 521, chapter: '9', type: 'vocab', zh: '結束', ja: ['終わる', '終わります'] },
  { id: 522, chapter: '9', type: 'vocab', zh: '出門、外出', ja: ['出かける', '出かけます'] },
  { id: 523, chapter: '9', type: 'vocab', zh: '出生、誕生', ja: ['生まれる', '生まれます'] },
  { id: 524, chapter: '9', type: 'vocab', zh: '下(雨)', ja: ['降る', '降ります'] },
  { id: 525, chapter: '9', type: 'vocab', zh: '拍攝', ja: ['撮る', '撮ります'] },
  { id: 526, chapter: '9', type: 'vocab', zh: '開(電器)', ja: ['つける', 'つけます'] },
  { id: 527, chapter: '9', type: 'vocab', zh: '關(電器)、擦掉', ja: ['消す', '消します'] },
  { id: 528, chapter: '9', type: 'vocab', zh: '忘記', ja: ['忘れる', '忘れます'] },
  { id: 529, chapter: '9', type: 'vocab', zh: '然後', ja: ['それから'] },
  { id: 530, chapter: '9', type: 'vocab', zh: '所以', ja: ['だから'] },
  { id: 531, chapter: '9', type: 'vocab', zh: '但是', ja: ['でも'] },
  { id: 5311, chapter: '9', type: 'vocab', zh: '冰冷的、冷淡的', ja: ['冷たい'] },
  { id: 532, chapter: '10', type: 'vocab', zh: '星期一', ja: ['月曜日'] },
  { id: 533, chapter: '10', type: 'vocab', zh: '星期二', ja: ['火曜日'] },
  { id: 534, chapter: '10', type: 'vocab', zh: '星期三', ja: ['水曜日'] },
  { id: 535, chapter: '10', type: 'vocab', zh: '星期四', ja: ['木曜日'] },
  { id: 536, chapter: '10', type: 'vocab', zh: '星期五', ja: ['金曜日'] },
  { id: 537, chapter: '10', type: 'vocab', zh: '星期六', ja: ['土曜日'] },
  { id: 538, chapter: '10', type: 'vocab', zh: '星期幾', ja: ['何曜日'] },
  { id: 539, chapter: '10', type: 'vocab', zh: '什麼時候', ja: ['いつ'] },
  { id: 540, chapter: '10', type: 'vocab', zh: '現在', ja: ['今'] },
  { id: 541, chapter: '10', type: 'vocab', zh: '生日', ja: ['誕生日'] },
  { id: 542, chapter: '10', type: 'vocab', zh: '除夕', ja: ['大晦日'] },
  { id: 543, chapter: '10', type: 'vocab', zh: '暑假', ja: ['夏休み'] },
  { id: 544, chapter: '10', type: 'vocab', zh: '寒假', ja: ['冬休み'] },
  { id: 545, chapter: '10', type: 'vocab', zh: '午休', ja: ['昼休み'] },
  { id: 546, chapter: '10', type: 'vocab', zh: '考試', ja: ['試験'] },
  { id: 547, chapter: '10', type: 'vocab', zh: '圖書館', ja: ['図書館'] },
  { id: 548, chapter: '10', type: 'vocab', zh: '東京', ja: ['東京'] },
  { id: 549, chapter: '10', type: 'vocab', zh: '沖繩、琉球', ja: ['沖縄'] },
  { id: 550, chapter: '10', type: 'vocab', zh: '香港', ja: ['香港'] },
  { id: 551, chapter: '10', type: 'vocab', zh: '電車、捷運', ja: ['電車'] },
  { id: 552, chapter: '10', type: 'vocab', zh: '飛機', ja: ['飛行機'] },
  { id: 553, chapter: '10', type: 'vocab', zh: '船舶', ja: ['船'] },
  { id: 554, chapter: '10', type: 'vocab', zh: '肥皂', ja: ['石鹸'] },
  { id: 555, chapter: '10', type: 'katakana', zh: '打工、工讀', ja: ['アルバイト'] },
  { id: 556, chapter: '10', type: 'katakana', zh: '音樂會、演唱會', ja: ['コンサート'] },
  { id: 557, chapter: '10', type: 'vocab', zh: '花費', ja: ['かかる', 'かかります'] },

  // Chapter 11~15 Vocab
  { id: 101, chapter: '11', type: 'katakana', zh: '菜單', ja: ['メニュー'] },
  { id: 102, chapter: '11', type: 'katakana', zh: '咖哩飯', ja: ['カレーライス'] },
  { id: 103, chapter: '11', type: 'katakana', zh: '拉麵', ja: ['ラーメン'] },
  { id: 104, chapter: '11', type: 'vocab', zh: '紅茶', ja: ['紅茶'] },
  { id: 105, chapter: '11', type: 'katakana', zh: '咖啡', ja: ['コーヒー'] },
  { id: 106, chapter: '11', type: 'vocab', zh: '蘋果', ja: ['林檎', 'りんご'] },
  { id: 107, chapter: '11', type: 'vocab', zh: '歡送會', ja: ['送別会'] },
  { id: 108, chapter: '11', type: 'katakana', zh: '禮物', ja: ['プレゼント'] },
  { id: 109, chapter: '11', type: 'katakana', zh: 'T恤', ja: ['Tシャツ'] },
  { id: 110, chapter: '11', type: 'vocab', zh: '機場', ja: ['空港'] },
  { id: 111, chapter: '11', type: 'katakana', zh: '冷氣', ja: ['クーラー'] },
  { id: 112, chapter: '11', type: 'vocab', zh: '後天', ja: ['明後日'] },
  { id: 113, chapter: '11', type: 'vocab', zh: '這週', ja: ['今週'] },
  { id: 114, chapter: '11', type: 'vocab', zh: '下週', ja: ['来週'] },
  { id: 115, chapter: '11', type: 'vocab', zh: '下個月', ja: ['来月'] },
  { id: 116, chapter: '11', type: 'vocab', zh: '一個', ja: ['1つ', '一つ'] },
  { id: 117, chapter: '11', type: 'vocab', zh: '兩個', ja: ['2つ', '二つ'] },
  { id: 118, chapter: '11', type: 'vocab', zh: '炎熱的、燙的', ja: ['暑い', '熱い'] },
  { id: 119, chapter: '11', type: 'vocab', zh: '短的、短暫的', ja: ['短い'] },
  { id: 120, chapter: '11', type: 'vocab', zh: '回去 (動・五)', ja: ['帰る', '帰ります'] },
  { id: 121, chapter: '11', type: 'vocab', zh: '來 (動・カ変)', ja: ['来る', '来ます'] },
  { id: 122, chapter: '11', type: 'vocab', zh: '再 (副詞)', ja: ['また'] },
  { id: 123, chapter: '12', type: 'vocab', zh: '時間', ja: ['時間'] },
  { id: 124, chapter: '12', type: 'vocab', zh: '自行車、腳踏車', ja: ['自転車'] },
  { id: 125, chapter: '12', type: 'katakana', zh: '機車、摩托車', ja: ['バイク'] },
  { id: 126, chapter: '12', type: 'vocab', zh: '我 (男性第一人稱)', ja: ['僕'] },
  { id: 127, chapter: '12', type: 'vocab', zh: '自己', ja: ['自分'] },
  { id: 128, chapter: '12', type: 'vocab', zh: '行李、手提物', ja: ['荷物'] },
  { id: 129, chapter: '12', type: 'vocab', zh: '午餐', ja: ['昼ご飯'] },
  { id: 130, chapter: '12', type: 'katakana', zh: '義大利麵', ja: ['スパゲッティ'] },
  { id: 131, chapter: '12', type: 'vocab', zh: '大碗、日式蓋飯的省略', ja: ['丼'] },
  { id: 132, chapter: '12', type: 'vocab', zh: '日式雞肉蛋蓋飯', ja: ['親子丼'] },
  { id: 133, chapter: '12', type: 'vocab', zh: '日式炸蝦蓋飯', ja: ['天丼'] },
  { id: 134, chapter: '12', type: 'katakana', zh: '啤酒', ja: ['ビール'] },
  { id: 135, chapter: '12', type: 'katakana', zh: '果汁', ja: ['ジュース'] },
  { id: 136, chapter: '12', type: 'vocab', zh: '家、家庭', ja: ['家', 'うち'] },
  { id: 137, chapter: '12', type: 'vocab', zh: '車站前', ja: ['駅前'] },
  { id: 138, chapter: '12', type: 'katakana', zh: '智慧型手機', ja: ['スマホ'] },
  { id: 139, chapter: '12', type: 'vocab', zh: '洗衣機', ja: ['洗濯機'] },
  { id: 140, chapter: '12', type: 'vocab', zh: '今年', ja: ['今年'] },
  { id: 141, chapter: '12', type: 'vocab', zh: '明年', ja: ['来年'] },
  { id: 143, chapter: '12', type: 'vocab', zh: '想要～、希望～', ja: ['欲しい'] },
  { id: 144, chapter: '12', type: 'vocab', zh: '拿、帶、擁有', ja: ['持つ', '持ちます'] },
  { id: 145, chapter: '12', type: 'vocab', zh: '幫助、幫忙', ja: ['手伝う', '手伝います'] },
  { id: 146, chapter: '12', type: 'vocab', zh: '（雨）停', ja: ['止む', '止みます'] },
  { id: 147, chapter: '12', type: 'vocab', zh: '做、創造、栽種', ja: ['作る', '作ります'] },
  { id: 148, chapter: '12', type: 'vocab', zh: '決定', ja: ['決める', '決めます'] },
  { id: 149, chapter: '12', type: 'vocab', zh: '練習', ja: ['練習する', '練習します'] },
  { id: 150, chapter: '12', type: 'vocab', zh: '還～、尚～', ja: ['まだ'] },
  { id: 151, chapter: '12', type: 'vocab', zh: '滿滿', ja: ['いっぱい'] },
  { id: 152, chapter: '12', type: 'vocab', zh: '已經', ja: ['もう'] },
  { id: 153, chapter: '12', type: 'sentence', zh: '是、知道了、遵命', ja: ['かしこまりました'] },
  { id: 154, chapter: '12', type: 'sentence', zh: '麻煩您、拜託', ja: ['お願いします'] },
  { id: 155, chapter: '13', type: 'vocab', zh: '名字', ja: ['名前'] },
  { id: 156, chapter: '13', type: 'vocab', zh: '地址', ja: ['住所'] },
  { id: 157, chapter: '13', type: 'vocab', zh: '電話號碼', ja: ['電話番号'] },
  { id: 158, chapter: '13', type: 'vocab', zh: '早餐', ja: ['朝ご飯'] },
  { id: 159, chapter: '13', type: 'vocab', zh: '晚餐', ja: ['晩ご飯'] },
  { id: 160, chapter: '13', type: 'vocab', zh: '牙齒', ja: ['歯'] },
  { id: 161, chapter: '13', type: 'vocab', zh: '臉', ja: ['顔'] },
  { id: 162, chapter: '13', type: 'vocab', zh: '每天', ja: ['毎日'] },
  { id: 163, chapter: '13', type: 'vocab', zh: '每天早上', ja: ['毎朝'] },
  { id: 164, chapter: '13', type: 'vocab', zh: '每天晚上', ja: ['毎晩'] },
  { id: 165, chapter: '13', type: 'vocab', zh: '洗澡、澡堂', ja: ['お風呂'] },
  { id: 166, chapter: '13', type: 'vocab', zh: '垃圾', ja: ['ごみ'] },
  { id: 167, chapter: '13', type: 'vocab', zh: '書店', ja: ['本屋'] },
  { id: 168, chapter: '13', type: 'vocab', zh: '出口', ja: ['出口'] },
  { id: 170, chapter: '13', type: 'katakana', zh: '新聞', ja: ['ニュース'] },
  { id: 171, chapter: '13', type: 'vocab', zh: '叫醒、引發', ja: ['起こす', '起こします'] },
  { id: 172, chapter: '13', type: 'sentence', zh: '刷（牙）', ja: ['歯を磨く', '歯を磨きます'] },
  { id: 173, chapter: '13', type: 'vocab', zh: '進入', ja: ['入る', '入ります'] },
  { id: 174, chapter: '13', type: 'vocab', zh: '坐、跪坐', ja: ['座る', '座ります'] },
  { id: 175, chapter: '13', type: 'vocab', zh: '拿出、提出、交出', ja: ['出す', '出します'] },
  { id: 176, chapter: '13', type: 'vocab', zh: '搭乘（交通工具）', ja: ['乗る', '乗ります'] },
  { id: 177, chapter: '13', type: 'vocab', zh: '說', ja: ['言う', '言います'] },
  { id: 178, chapter: '13', type: 'vocab', zh: '見面', ja: ['会う', '会います'] },
  { id: 179, chapter: '13', type: 'sentence', zh: '提款、領錢', ja: ['お金を下ろす', 'お金を下ろします'] },
  { id: 180, chapter: '13', type: 'vocab', zh: '教、告訴', ja: ['教える', '教えます'] },
  { id: 181, chapter: '13', type: 'vocab', zh: '丟掉、拋棄', ja: ['捨てる', '捨てます'] },
  { id: 182, chapter: '13', type: 'vocab', zh: '關、關掉', ja: ['閉める', '閉めます'] },
  { id: 183, chapter: '13', type: 'vocab', zh: '打電話', ja: ['電話する', '電話します'] },
  { id: 184, chapter: '13', type: 'vocab', zh: '洗衣服', ja: ['洗濯する', '洗濯します'] },
  { id: 185, chapter: '13', type: 'vocab', zh: '再一次', ja: ['もう一度'] },
  { id: 186, chapter: '13', type: 'vocab', zh: '慢慢地', ja: ['ゆっくり'] },
  { id: 187, chapter: '13', type: 'vocab', zh: '請～', ja: ['どうぞ'] },
  { id: 188, chapter: '13', type: 'sentence', zh: '就這麼決定、就這麼辦吧', ja: ['そうしましょう'] },
  { id: 189, chapter: '14', type: 'katakana', zh: '紐約', ja: ['ニューヨーク'] },
  { id: 190, chapter: '14', type: 'vocab', zh: '藝術', ja: ['芸術'] },
  { id: 191, chapter: '14', type: 'katakana', zh: '客廳', ja: ['リビングルーム'] },
  { id: 192, chapter: '14', type: 'vocab', zh: '眼鏡', ja: ['眼鏡'] },
  { id: 193, chapter: '14', type: 'katakana', zh: '毛衣', ja: ['セーター'] },
  { id: 194, chapter: '14', type: 'katakana', zh: '裙子', ja: ['スカート'] },
  { id: 195, chapter: '14', type: 'katakana', zh: '領帶', ja: ['ネクタイ'] },
  { id: 196, chapter: '14', type: 'vocab', zh: '最近', ja: ['最近'] },
  { id: 197, chapter: '14', type: 'vocab', zh: '最近、近來', ja: ['この頃', 'このごろ'] },
  { id: 198, chapter: '14', type: 'vocab', zh: '歌、歌曲', ja: ['歌'] },
  { id: 199, chapter: '14', type: 'katakana', zh: '游泳池', ja: ['プール'] },
  { id: 200, chapter: '14', type: 'katakana', zh: '網球', ja: ['テニス'] },
  { id: 201, chapter: '14', type: 'katakana', zh: '網球場', ja: ['テニスコート'] },
  { id: 202, chapter: '14', type: 'katakana', zh: '卡拉OK', ja: ['カラオケ'] },
  { id: 203, chapter: '14', type: 'vocab', zh: '書信', ja: ['手紙'] },
  { id: 204, chapter: '14', type: 'vocab', zh: '從前、過往', ja: ['昔'] },
  { id: 205, chapter: '14', type: 'vocab', zh: '好朋友', ja: ['仲良し'] },
  { id: 206, chapter: '14', type: 'vocab', zh: '好友、親近的朋友', ja: ['親友'] },
  { id: 208, chapter: '14', type: 'vocab', zh: '眼睛', ja: ['目'] },
  { id: 210, chapter: '14', type: 'vocab', zh: '黃的、黃色', ja: ['黄色い'] },
  { id: 211, chapter: '14', type: 'vocab', zh: '白的、白色', ja: ['白い'] },
  { id: 212, chapter: '14', type: 'vocab', zh: '甜的', ja: ['甘い'] },
  { id: 213, chapter: '14', type: 'vocab', zh: '彈', ja: ['弾く', '弾きます'] },
  { id: 214, chapter: '14', type: 'vocab', zh: '唱（歌）', ja: ['歌う', '歌います'] },
  { id: 215, chapter: '14', type: 'vocab', zh: '游泳', ja: ['泳ぐ', '泳ぎます'] },
  { id: 216, chapter: '14', type: 'vocab', zh: '居住', ja: ['住む', '住みます'] },
  { id: 217, chapter: '14', type: 'vocab', zh: '穿（下半身衣物）', ja: ['履く', '穿く', '履きます', '穿きます'] },
  { id: 218, chapter: '14', type: 'vocab', zh: '穿（連身、上半身衣物）', ja: ['着る', '着ます'] },
  { id: 219, chapter: '14', type: 'vocab', zh: '掛（眼鏡）', ja: ['かける', 'かけます'] },
  { id: 220, chapter: '14', type: 'vocab', zh: '永遠、始終', ja: ['いつまでも'] },
  { id: 221, chapter: '14', type: 'vocab', zh: '經常', ja: ['よく'] },
  { id: 222, chapter: '15', type: 'vocab', zh: '道路', ja: ['道'] },
  { id: 223, chapter: '15', type: 'vocab', zh: '衣服', ja: ['洋服'] },
  { id: 224, chapter: '15', type: 'vocab', zh: '大聲（說話）', ja: ['大声'] },
  { id: 225, chapter: '15', type: 'vocab', zh: '他人、別人', ja: ['他人'] },
  { id: 226, chapter: '15', type: 'vocab', zh: '壞話', ja: ['悪口'] },
  { id: 227, chapter: '15', type: 'vocab', zh: '部長', ja: ['部長'] },
  { id: 228, chapter: '15', type: 'katakana', zh: '禮節', ja: ['マナー'] },
  { id: 229, chapter: '15', type: 'vocab', zh: '草坪、草地', ja: ['芝生'] },
  { id: 231, chapter: '15', type: 'katakana', zh: '香菸', ja: ['タバコ'] },
  { id: 232, chapter: '15', type: 'vocab', zh: '感冒', ja: ['風邪'] },
  { id: 233, chapter: '15', type: 'vocab', zh: '規章須知、體會', ja: ['心得'] },
  { id: 234, chapter: '15', type: 'vocab', zh: '電源', ja: ['電源'] },
  { id: 235, chapter: '15', type: 'vocab', zh: '共用', ja: ['共用'] },
  { id: 236, chapter: '15', type: 'vocab', zh: '大門口、玄關', ja: ['玄関'] },
  { id: 237, chapter: '15', type: 'katakana', zh: '門', ja: ['ドア'] },
  { id: 238, chapter: '15', type: 'vocab', zh: '生活', ja: ['生活'] },
  { id: 239, chapter: '15', type: 'vocab', zh: '玩耍', ja: ['遊ぶ', '遊びます'] },
  { id: 240, chapter: '15', type: 'vocab', zh: '說、說話', ja: ['話す', '話します'] },
  { id: 241, chapter: '15', type: 'vocab', zh: '使用', ja: ['使う', '使います'] },
  { id: 242, chapter: '15', type: 'vocab', zh: '休息、放假', ja: ['休む', '休みます'] },
  { id: 243, chapter: '15', type: 'vocab', zh: '吸', ja: ['吸う', '吸います'] },
  { id: 244, chapter: '15', type: 'vocab', zh: '切、砍、剪、斬', ja: ['切る', '切ります'] },
  { id: 245, chapter: '15', type: 'vocab', zh: '度過、生活', ja: ['過ごす', '過ごします'] },
  { id: 246, chapter: '15', type: 'vocab', zh: '開、打開', ja: ['開ける', '開けます'] },
  { id: 247, chapter: '15', type: 'vocab', zh: '試穿', ja: ['試着する', '試着します'] },
  { id: 248, chapter: '15', type: 'vocab', zh: '說明', ja: ['説明する', '説明します'] },
  { id: 249, chapter: '15', type: 'vocab', zh: '商量', ja: ['相談する', '相談します'] },
  { id: 250, chapter: '15', type: 'vocab', zh: '詢問、提問', ja: ['質問する', '質問します'] },
  { id: 251, chapter: '15', type: 'vocab', zh: '遲到', ja: ['遅刻する', '遅刻します'] },
  { id: 252, chapter: '15', type: 'vocab', zh: '打掃', ja: ['掃除する', '掃除します'] },
  { id: 253, chapter: '15', type: 'vocab', zh: '那麼', ja: ['それでは'] },

  // Chapter 11~15 Grammar
  { id: 601, chapter: '11', type: 'grammar', zh: '請給我菜單。', ja: ['メニューをください'] },
  { id: 602, chapter: '11', type: 'grammar', zh: '請給我一份咖哩飯。', ja: ['カレーライスを1つください', 'カレーライスを一つください'] },
  { id: 603, chapter: '11', type: 'grammar', zh: '請給我三本筆記本。', ja: ['ノートを3冊ください'] },
  { id: 604, chapter: '11', type: 'grammar', zh: '下週要去日本。', ja: ['来週日本へ行きます'] },
  { id: 605, chapter: '11', type: 'grammar', zh: '朋友明天會來我家。', ja: ['友達は明日私の家へ来ます'] },
  { id: 606, chapter: '11', type: 'grammar', zh: '什麼時候要回東京？', ja: ['いつ東京へ帰りますか'] },
  { id: 607, chapter: '11', type: 'grammar', zh: '因為很冷，所以喝熱紅茶。', ja: ['寒いですから、熱い紅茶を飲みます'] },
  { id: 608, chapter: '11', type: 'grammar', zh: '因為很便宜，所以買了。', ja: ['安いですから、買いました'] },
  { id: 609, chapter: '11', type: 'grammar', zh: '因為非常喜歡水果。', ja: ['果物がとても好きですから'] },
  { id: 610, chapter: '11', type: 'grammar', zh: '因為下個月鈴木先生要回東京，所以要辦歡送會。', ja: ['来月鈴木さんが東京へ帰りますから、送別会をします'] },
  { id: 611, chapter: '11', type: 'grammar', zh: '什麼比較好呢？', ja: ['何がいいですか'] },
  { id: 612, chapter: '11', type: 'grammar', zh: '誰要去呢？', ja: ['誰が行きますか'] },
  { id: 613, chapter: '12', type: 'grammar', zh: '好熱。想喝點冷飲呢。', ja: ['暑いです。何か冷たいものが飲みたいですね'] },
  { id: 614, chapter: '12', type: 'grammar', zh: '我明年想買新車。', ja: ['私は、来年新しい車を買いたいです'] },
  { id: 615, chapter: '12', type: 'grammar', zh: '我想要腳踏車。', ja: ['私は自転車が欲しいです'] },
  { id: 616, chapter: '12', type: 'grammar', zh: '小時候，我想要自己的房間。', ja: ['子供の時、自分の部屋が欲しかったです'] },
  { id: 617, chapter: '12', type: 'grammar', zh: '現在什麼都不想要。', ja: ['今は、何も欲しくありません'] },
  { id: 618, chapter: '12', type: 'grammar', zh: '今年的生日禮物想要什麼？', ja: ['今年の誕生日のプレゼントは何が欲しいですか'] },
  { id: 619, chapter: '12', type: 'grammar', zh: '我來拿行李吧。', ja: ['荷物を持ちましょうか'] },
  { id: 620, chapter: '12', type: 'grammar', zh: '我來幫忙吧。', ja: ['手伝いましょうか'] },
  { id: 621, chapter: '12', type: 'grammar', zh: '一起去吧。', ja: ['一緒に行きましょう'] },
  { id: 622, chapter: '12', type: 'grammar', zh: '已經決定好學校了嗎？', ja: ['もう学校を決めましたか'] },
  { id: 623, chapter: '12', type: 'grammar', zh: '已經吃過午餐了嗎？', ja: ['もう昼ご飯を食べましたか'] },
  { id: 624, chapter: '12', type: 'grammar', zh: '還沒。不過已經買了便當。', ja: ['まだです。でももうお弁当を買いました'] },
  { id: 625, chapter: '12', type: 'grammar', zh: '已經要回家了嗎？', ja: ['もう家へ帰りますか'] },
  { id: 626, chapter: '12', type: 'grammar', zh: '還在下雨嗎？', ja: ['まだ雨ですか'] },
  { id: 627, chapter: '12', type: 'grammar', zh: '不，已經停了。', ja: ['いいえ、もう止みました'] },
  { id: 628, chapter: '13', type: 'grammar', zh: '請吃。', ja: ['どうぞ食べてください'] },
  { id: 629, chapter: '13', type: 'grammar', zh: '不好意思，請告訴我您的名字。', ja: ['すみません、お名前を教えてください'] },
  { id: 630, chapter: '13', type: 'grammar', zh: '請把地址寫在這裡。', ja: ['ここにご住所を書いてください'] },
  { id: 631, chapter: '13', type: 'grammar', zh: '去百貨公司買東西。', ja: ['デパートへ行って、買い物します'] },
  { id: 632, chapter: '13', type: 'grammar', zh: '做好早餐叫小孩起床。', ja: ['朝ご飯を作って、子供を起こします'] },
  { id: 633, chapter: '13', type: 'grammar', zh: '刷牙洗臉。', ja: ['歯を磨いて、顔を洗いました'] },
  { id: 634, chapter: '13', type: 'grammar', zh: '每天早上起床後運動。', ja: ['毎朝、起きてから運動します'] },
  { id: 635, chapter: '13', type: 'grammar', zh: '吃完早餐後出門。', ja: ['朝ご飯を食べてから、出かけます'] },
  { id: 636, chapter: '13', type: 'grammar', zh: '每天晚上洗完澡後吃飯。', ja: ['毎晩、お風呂に入ってから食事します'] },
  { id: 637, chapter: '14', type: 'grammar', zh: '現在媽媽正在洗衣服。', ja: ['今、母は洗濯しています'] },
  { id: 638, chapter: '14', type: 'grammar', zh: '爸爸正在客廳看雜誌。', ja: ['父はリビングルームで雑誌を読んでいます'] },
  { id: 639, chapter: '14', type: 'grammar', zh: '現在姐姐正在彈鋼琴。', ja: ['今、姉はピアノを弾いています'] },
  { id: 640, chapter: '14', type: 'grammar', zh: '她戴著眼鏡。', ja: ['彼女は眼鏡をかけています'] },
  { id: 641, chapter: '14', type: 'grammar', zh: '老師穿著黃色的毛衣。', ja: ['先生は黄色いセーターを着ています'] },
  { id: 642, chapter: '14', type: 'grammar', zh: '林先生住在淡水。', ja: ['林さんは淡水に住んでいます'] },
  { id: 643, chapter: '14', type: 'grammar', zh: '常看電影。', ja: ['よく映画を見ます'] },
  { id: 644, chapter: '14', type: 'grammar', zh: '最近常騎腳踏車。', ja: ['最近、よく自転車に乗ります'] },
  { id: 645, chapter: '14', type: 'grammar', zh: '高中時，常在學校跟朋友打網球。', ja: ['高校の時、よく学校で友達とテニスをしました'] },
  { id: 646, chapter: '14', type: 'grammar', zh: '我不常喝咖啡。', ja: ['私はあまりコーヒーを飲みません'] },
  { id: 647, chapter: '14', type: 'grammar', zh: '她不常吃甜食。', ja: ['彼女はあまり甘いものを食べません'] },
  { id: 648, chapter: '14', type: 'grammar', zh: '最近不常回家。', ja: ['この頃、あまり家へ帰りません'] },
  { id: 649, chapter: '15', type: 'grammar', zh: '可以試穿這件衣服。', ja: ['この洋服を試着してもいいです'] },
  { id: 650, chapter: '15', type: 'grammar', zh: '不好意思，可以看這本雜誌嗎？', ja: ['すみません、この雑誌を読んでもいいですか'] },
  { id: 651, chapter: '15', type: 'grammar', zh: '可以吃冰箱裡的蛋糕嗎？', ja: ['冷蔵庫のケーキを食べてもいいですか'] },
  { id: 652, chapter: '15', type: 'grammar', zh: '可以用鉛筆寫嗎？', ja: ['鉛筆で書いてもいいですか'] },
  { id: 653, chapter: '15', type: 'grammar', zh: '考試時不可以和旁邊的人說話。', ja: ['試験の時、隣の人と話してはいけません'] },
  { id: 654, chapter: '15', type: 'grammar', zh: '圖書館裡不可以大聲喧嘩。', ja: ['図書館で大声を出してはいけません'] },
  { id: 655, chapter: '15', type: 'grammar', zh: '不可以吃太多甜食。', ja: ['甘いものをたくさん食べてはいけません'] },
  { id: 656, chapter: '15', type: 'grammar', zh: '不可以在海裡游泳。', ja: ['海で泳いではいけません'] },
  { id: 657, chapter: '15', type: 'grammar', zh: '不可以說別人的壞話。', ja: ['他人の悪口を言ってはいけません'] },
  { id: 658, chapter: '15', type: 'grammar', zh: '關於旅行為您做說明。請仔細聽。', ja: ['旅行について、ご説明します。よく聞いてください'] },
  { id: 659, chapter: '15', type: 'grammar', zh: '關於下週的工作，請和部長好好商量。', ja: ['来週の仕事について、部長とよく相談してください'] },
  { id: 660, chapter: '15', type: 'grammar', zh: '我寫了關於日本用餐禮儀的報告。', ja: ['日本の食事マナーについて、レポートを書きました'] },

  // Chapter 1~15 Sentence Translations
  { id: 701, chapter: '1', type: 'sentence', zh: '爸爸是公務員。', ja: ['お父さんは公務員です'] },
  { id: 702, chapter: '1', type: 'sentence', zh: '她是學生。', ja: ['彼女は学生です'] },
  { id: 703, chapter: '1', type: 'sentence', zh: '老師是英國人。', ja: ['先生はイギリス人です'] },
  { id: 704, chapter: '1', type: 'sentence', zh: '姐姐是公司職員。', ja: ['お姉さんは会社員です'] },
  { id: 705, chapter: '1', type: 'sentence', zh: '張先生是老師嗎。', ja: ['張さんは先生ですか'] },
  { id: 706, chapter: '1', type: 'sentence', zh: '韓語課的老師是韓國人嗎。', ja: ['韓国語の授業の先生は韓国人ですか'] },
  { id: 707, chapter: '1', type: 'sentence', zh: '你是淡江大學的學生嗎。', ja: ['あなたは淡江大学の学生ですか'] },
  { id: 708, chapter: '1', type: 'sentence', zh: '他是英語老師嗎。', ja: ['彼は英語の先生ですか'] },
  { id: 709, chapter: '1', type: 'sentence', zh: '媽媽不是公務員。', ja: ['お母さんは公務員ではありません'] },
  { id: 710, chapter: '1', type: 'sentence', zh: '我的主修不是英語。', ja: ['私の専攻は英語ではありません'] },
  { id: 711, chapter: '1', type: 'sentence', zh: '他不是日本人。', ja: ['彼は日本人ではありません'] },
  { id: 712, chapter: '1', type: 'sentence', zh: '我不是公司職員。', ja: ['私は会社員ではありません'] },
  { id: 713, chapter: '2', type: 'sentence', zh: '那是中文的雜誌。', ja: ['それは中国語の雑誌です'] },
  { id: 714, chapter: '2', type: 'sentence', zh: '我的筆記本是那個。', ja: ['私のノートはあれです'] },
  { id: 715, chapter: '2', type: 'sentence', zh: '你的包包是哪一個。', ja: ['あなたの鞄はどれですか'] },
  { id: 716, chapter: '2', type: 'sentence', zh: '這是什麼。', ja: ['これは何ですか'] },
  { id: 717, chapter: '2', type: 'sentence', zh: '這個水壺是我的。', ja: ['この水筒は私のです'] },
  { id: 718, chapter: '2', type: 'sentence', zh: '那支原子筆是老師的。', ja: ['そのボールペンは先生のです'] },
  { id: 719, chapter: '2', type: 'sentence', zh: '那隻手錶是誰的。', ja: ['あの時計は誰のですか'] },
  { id: 720, chapter: '2', type: 'sentence', zh: '這是桌子。那也是桌子。', ja: ['これは机です。あれも机です'] },
  { id: 721, chapter: '2', type: 'sentence', zh: '這是教科書。那也是教科書。', ja: ['これは教科書です。それも教科書です'] },
  { id: 722, chapter: '2', type: 'sentence', zh: '這是英文雜誌還是日文雜誌。', ja: ['これは英語の雑誌ですか、日本語の雑誌ですか'] },
  { id: 723, chapter: '2', type: 'sentence', zh: '小野小姐是老師還是公司職員。', ja: ['小野さんは先生ですか、会社員ですか'] },
  { id: 724, chapter: '3', type: 'sentence', zh: '這是紅色的傘。', ja: ['これは赤い傘です'] },
  { id: 725, chapter: '3', type: 'sentence', zh: '那是小椅子。', ja: ['それは小さい椅子です'] },
  { id: 726, chapter: '3', type: 'sentence', zh: '那是貴的電視。', ja: ['あれは高いテレビです'] },
  { id: 727, chapter: '3', type: 'sentence', zh: '不好吃。', ja: ['美味しくないです'] },
  { id: 728, chapter: '3', type: 'sentence', zh: '不重。', ja: ['重くないです'] },
  { id: 729, chapter: '3', type: 'sentence', zh: '不舊。', ja: ['古くないです'] },
  { id: 730, chapter: '3', type: 'sentence', zh: '不太好。', ja: ['あまり良くないです', 'あまりよくないです'] },
  { id: 731, chapter: '3', type: 'sentence', zh: '非常大。', ja: ['とても大きいです'] },
  { id: 732, chapter: '3', type: 'sentence', zh: '不太輕。', ja: ['あまり軽くないです'] },
  { id: 733, chapter: '4', type: 'sentence', zh: '這座公園很安靜。', ja: ['この公園は静かです'] },
  { id: 734, chapter: '4', type: 'sentence', zh: '台灣的新幹線很方便。', ja: ['台湾の新幹線は便利です'] },
  { id: 735, chapter: '4', type: 'sentence', zh: '小丸子是有活力的小孩。', ja: ['丸子は元気な子供です'] },
  { id: 736, chapter: '4', type: 'sentence', zh: '生魚片是不擅長的食物。', ja: ['刺身は苦手な食べ物です'] },
  { id: 737, chapter: '4', type: 'sentence', zh: '張先生喜歡芒果剉冰。', ja: ['張さんはマンゴーかき氷が好きです'] },
  { id: 738, chapter: '4', type: 'sentence', zh: '蔡小姐討厭納豆。', ja: ['蔡さんは納豆が嫌いです'] },
  { id: 739, chapter: '4', type: 'sentence', zh: '我法文很差。', ja: ['私はフランス語が下手です'] },
  { id: 740, chapter: '4', type: 'sentence', zh: '田中先生的房間比我的房間寬敞。', ja: ['田中さんの部屋は私の部屋より広いです'] },
  { id: 741, chapter: '4', type: 'sentence', zh: '哥哥的電子辭典比我的舊。', ja: ['お兄さんの電子辞書は私のより古いです'] },
  { id: 742, chapter: '4', type: 'sentence', zh: '陳小姐的傘比林小姐的輕。', ja: ['陳さんの傘は林さんのより軽いです'] },
  { id: 743, chapter: '5', type: 'sentence', zh: '昨天的電影很有趣。', ja: ['昨日の映画は面白かったです'] },
  { id: 744, chapter: '5', type: 'sentence', zh: '上星期天的派對很好玩。', ja: ['先週の日曜日のパーティーは楽しかったです'] },
  { id: 745, chapter: '5', type: 'sentence', zh: '這家便利商店的三明治很便宜。', ja: ['このコンビニのサンドイッチは安かったです'] },
  { id: 746, chapter: '5', type: 'sentence', zh: '電子辭典以前不新。', ja: ['電子辞書は新しくなかったです'] },
  { id: 747, chapter: '5', type: 'sentence', zh: '我的房間以前不寬敞。', ja: ['私の部屋は広くなかったです'] },
  { id: 748, chapter: '5', type: 'sentence', zh: '電腦教室以前不暗。', ja: ['パソコン教室は暗くなかったです'] },
  { id: 749, chapter: '5', type: 'sentence', zh: '昨天的作業很簡單。', ja: ['昨日の宿題は簡単でした'] },
  { id: 750, chapter: '5', type: 'sentence', zh: '派對以前不熱鬧。', ja: ['パーティーは賑やかではありませんでした'] },
  { id: 751, chapter: '5', type: 'sentence', zh: '高中時，沒有空閒。', ja: ['高校の時、暇ではありませんでした'] },
  { id: 752, chapter: '5', type: 'sentence', zh: '那是一趟開心的旅行。', ja: ['それは楽しい旅行でした'] },
  { id: 753, chapter: '5', type: 'sentence', zh: '那不是一趟開心的旅行。', ja: ['それは楽しい旅行ではありませんでした'] },
  { id: 754, chapter: '6', type: 'sentence', zh: '淡江大學在淡水。', ja: ['淡江大学は淡水にあります'] },
  { id: 755, chapter: '6', type: 'sentence', zh: '鉛筆在包包裡。', ja: ['鉛筆は鞄の中にあります'] },
  { id: 756, chapter: '6', type: 'sentence', zh: '貓在書架上。', ja: ['猫は本棚の上にいます'] },
  { id: 757, chapter: '6', type: 'sentence', zh: '醫院不在車站前。', ja: ['病院は駅の前にありません'] },
  { id: 758, chapter: '6', type: 'sentence', zh: '我不在大學裡。', ja: ['私は大学にいません'] },
  { id: 759, chapter: '6', type: 'sentence', zh: '林小姐和陳小姐在學校。', ja: ['林さんと陳さんは学校にいます'] },
  { id: 760, chapter: '6', type: 'sentence', zh: '爸爸和媽媽在淡水。', ja: ['父と母は淡水にいます'] },
  { id: 761, chapter: '6', type: 'sentence', zh: '百貨公司和電影院在車站前。', ja: ['デパートと映画館は駅の前にあります'] },
  { id: 762, chapter: '7', type: 'sentence', zh: '桌子底下有貓。', ja: ['机の下に猫がいます'] },
  { id: 763, chapter: '7', type: 'sentence', zh: '冰箱裡有兩根香蕉。', ja: ['冷蔵庫にバナナが2本あります'] },
  { id: 764, chapter: '7', type: 'sentence', zh: '書架上有五本日文書。', ja: ['本棚に日本語の本が5冊あります'] },
  { id: 765, chapter: '7', type: 'sentence', zh: '學校前面有三個學生。', ja: ['学校の前に学生が3人います'] },
  { id: 766, chapter: '7', type: 'sentence', zh: '抽屜裡面有什麼嗎。是的，有鉛筆。', ja: ['引出しの中に何かありますか。はい、鉛筆があります'] },
  { id: 767, chapter: '7', type: 'sentence', zh: '房間外面有誰在嗎。不，沒有人在。', ja: ['部屋の外に誰かいますか。いいえ、誰もいません'] },
  { id: 768, chapter: '8', type: 'sentence', zh: '不聽音樂。', ja: ['音楽を聴きません', '音楽を聞きません'] },
  { id: 769, chapter: '8', type: 'sentence', zh: '洗手。', ja: ['手を洗います'] },
  { id: 770, chapter: '8', type: 'sentence', zh: '不看電視。', ja: ['テレビを見ません'] },
  { id: 771, chapter: '8', type: 'sentence', zh: '在便利商店買便當。', ja: ['コンビニで弁当を買います'] },
  { id: 772, chapter: '8', type: 'sentence', zh: '在公園吃點心。', ja: ['公園でお菓子を食べます'] },
  { id: 773, chapter: '8', type: 'sentence', zh: '在庭院運動。', ja: ['庭で運動します'] },
  { id: 774, chapter: '8', type: 'sentence', zh: '要不要一起寫報告呢。', ja: ['一緒にレポートを書きませんか'] },
  { id: 775, chapter: '8', type: 'sentence', zh: '要不要一起喝酒呢。', ja: ['一緒にお酒を飲みませんか'] },
  { id: 776, chapter: '9', type: 'sentence', zh: '昨天拍照了。', ja: ['昨日、写真を撮りました'] },
  { id: 777, chapter: '9', type: 'sentence', zh: '今天早上沒有關電燈。', ja: ['今朝、電気を消しませんでした'] },
  { id: 778, chapter: '9', type: 'sentence', zh: '昨晚沒有看電視。', ja: ['夕べ、テレビを見ませんでした'] },
  { id: 779, chapter: '9', type: 'sentence', zh: '總是晚上11點睡覺。', ja: ['いつも夜11時に寝ます'] },
  { id: 780, chapter: '9', type: 'sentence', zh: '明天幾點要出門。', ja: ['明日、何時に出かけますか'] },
  { id: 781, chapter: '9', type: 'sentence', zh: '今天早上幾點吃早餐的。', ja: ['今朝、何時にご飯を食べましたか'] },
  { id: 782, chapter: '9', type: 'sentence', zh: '手很大。', ja: ['手が大きいです'] },
  { id: 783, chapter: '9', type: 'sentence', zh: '天氣不好。', ja: ['天気が良くないです', '天気がよくないです'] },
  { id: 784, chapter: '9', type: 'sentence', zh: '是的，下雨了。', ja: ['はい、雨が降りました'] },
  { id: 785, chapter: '9', type: 'sentence', zh: '在2000年出生。', ja: ['2000年に生まれました'] },
  { id: 786, chapter: '9', type: 'sentence', zh: '上午9點出門。', ja: ['午前9時に出かけます'] },
  { id: 787, chapter: '9', type: 'sentence', zh: '是的，關掉了。', ja: ['はい、消しました'] },
  { id: 788, chapter: '10', type: 'sentence', zh: '從9點15分開始。', ja: ['9時15分からです'] },
  { id: 789, chapter: '10', type: 'sentence', zh: '到5點半為止。', ja: ['5時半までです'] },
  { id: 790, chapter: '10', type: 'sentence', zh: '從12點到1點為止。', ja: ['12時から1時までです'] },
  { id: 791, chapter: '10', type: 'sentence', zh: '從7月到8月為止。', ja: ['7月から8月までです'] },
  { id: 792, chapter: '10', type: 'sentence', zh: '晚上10點到11點寫了作業。', ja: ['夜10時から11時まで宿題をしました'] },
  { id: 793, chapter: '10', type: 'sentence', zh: '星期二到星期五在餐廳打工。', ja: ['火曜日から金曜日までレストランでアルバイトをします'] },
  { id: 794, chapter: '10', type: 'sentence', zh: '待到除夕為止。', ja: ['大晦日までいます'] },
  { id: 795, chapter: '10', type: 'sentence', zh: '用肥皂洗手。', ja: ['石鹸で手を洗います'] },
  { id: 796, chapter: '10', type: 'sentence', zh: '搭船從台灣到沖繩要花12小時。', ja: ['台湾から沖縄まで船で12時間かかります'] },
  { id: 797, chapter: '11', type: 'sentence', zh: '請給我一杯咖啡。', ja: ['コーヒーを1つください', 'コーヒーを一つください'] },
  { id: 798, chapter: '11', type: 'sentence', zh: '請給我三支鉛筆。', ja: ['鉛筆を3本ください'] },
  { id: 799, chapter: '11', type: 'sentence', zh: '明天去郵局。', ja: ['明日、郵便局へ行きます'] },
  { id: 800, chapter: '11', type: 'sentence', zh: '昨天沒有回家。', ja: ['昨日、家へ帰りませんでした'] },
  { id: 801, chapter: '11', type: 'sentence', zh: '今天不去學校。', ja: ['今日、学校へ行きません'] },
  { id: 802, chapter: '11', type: 'sentence', zh: '因為喜歡日本，所以學習日文。', ja: ['日本が好きですから、日本語を勉強します'] },
  { id: 803, chapter: '11', type: 'sentence', zh: '因為沒有錢，所以昨晚沒吃飯。', ja: ['お金がありませんから、夕べご飯を食べませんでした'] },
  { id: 804, chapter: '11', type: 'sentence', zh: '因為美國有朋友，所以下個月要去美國。', ja: ['アメリカに友達がいますから、来月アメリカへ行きます'] },
  { id: 805, chapter: '12', type: 'sentence', zh: '想喝果汁。', ja: ['ジュースを飲みたいです'] },
  { id: 806, chapter: '12', type: 'sentence', zh: '想買手錶。', ja: ['時計を買いたいです'] },
  { id: 807, chapter: '12', type: 'sentence', zh: '想聽音樂。', ja: ['音楽を聴きたいです', '音楽を聞きたいです'] },
  { id: 808, chapter: '12', type: 'sentence', zh: '想要去旅行。', ja: ['旅行をしたいです'] },
  { id: 809, chapter: '12', type: 'sentence', zh: '不想要冰箱。想要洗衣機。', ja: ['冷蔵庫は欲しくないです。洗濯機が欲しいです'] },
  { id: 810, chapter: '12', type: 'sentence', zh: '不想要電腦。想要智慧型手機。', ja: ['パソコンは欲しくないです。スマホが欲しいです'] },
  { id: 811, chapter: '12', type: 'sentence', zh: '不想要車子。想要機車。', ja: ['車は欲しくないです。バイクが欲しいです'] },
  { id: 812, chapter: '12', type: 'sentence', zh: '不想要辭典。想要電子辭典。', ja: ['辞書は欲しくないです。電子辞書が欲しいです'] },
  { id: 813, chapter: '12', type: 'sentence', zh: '做料理吧。', ja: ['料理を作りましょう'] },
  { id: 814, chapter: '12', type: 'sentence', zh: '吃炸蝦蓋飯吧。', ja: ['天丼を食べましょう'] },
  { id: 815, chapter: '12', type: 'sentence', zh: '寫作業吧。', ja: ['宿題をしましょう'] },
  { id: 816, chapter: '13', type: 'sentence', zh: '請讀這本雜誌。', ja: ['どうぞ、この雑誌を読んでください'] },
  { id: 817, chapter: '13', type: 'sentence', zh: '請丟垃圾。', ja: ['ごみを出してください'] },
  { id: 818, chapter: '13', type: 'sentence', zh: '請打電話給我。', ja: ['私に電話してください'] },
  { id: 819, chapter: '13', type: 'sentence', zh: '請把舊報紙丟掉。', ja: ['古い新聞を捨ててください'] },
  { id: 820, chapter: '13', type: 'sentence', zh: '每天搭電車去公司。', ja: ['毎日、電車に乗って、会社へ行きます'] },
  { id: 821, chapter: '13', type: 'sentence', zh: '回家吃晚餐。', ja: ['うちへ帰って、晩ご飯を食べます'] },
  { id: 822, chapter: '13', type: 'sentence', zh: '去書店買了日文辭典。', ja: ['本屋へ行って、日本語の辞書を買いました'] },
  { id: 823, chapter: '13', type: 'sentence', zh: '昨晚念書到九點，看了電視後睡覺了。', ja: ['夕べ、9時まで勉強して、テレビを見て、寝ました'] },
  { id: 824, chapter: '13', type: 'sentence', zh: '關窗戶後睡覺。', ja: ['窓を閉めてから、寝ます'] },
  { id: 825, chapter: '13', type: 'sentence', zh: '爸爸每天早上看完新聞後去公司。', ja: ['父は毎朝、ニュースを見てから、会社へ行きます'] },
  { id: 826, chapter: '13', type: 'sentence', zh: '星期天起床後洗衣服。', ja: ['日曜日、起きてから、洗濯します'] },
  { id: 827, chapter: '13', type: 'sentence', zh: '在郵局領錢後去學校。', ja: ['郵便局でお金を下ろしてから、学校へ行きます'] },
  { id: 828, chapter: '13', type: 'sentence', zh: '每天晚上回家後要做什麼。', ja: ['毎晩、うちへ帰ってから、何をしますか'] },
  { id: 829, chapter: '14', type: 'sentence', zh: '李先生正在拍照。', ja: ['李さんは写真を撮っています'] },
  { id: 830, chapter: '14', type: 'sentence', zh: '媽媽正在百貨公司買東西。', ja: ['母はデパートで買い物しています'] },
  { id: 831, chapter: '14', type: 'sentence', zh: '林先生正在游泳池游泳。', ja: ['林さんはプールで泳いでいます'] },
  { id: 832, chapter: '14', type: 'sentence', zh: '現在姐姐正在看電視。', ja: ['今、姉はテレビを見ています'] },
  { id: 833, chapter: '14', type: 'sentence', zh: '弟弟穿著黃色T恤。', ja: ['弟は黄色いTシャツを着ています'] },
  { id: 834, chapter: '14', type: 'sentence', zh: '田中先生戴著黑框眼鏡。', ja: ['田中さんは黒い眼鏡をかけています'] },
  { id: 835, chapter: '14', type: 'sentence', zh: '哥哥打著白領帶。', ja: ['兄は白いネクタイをしています'] },
  { id: 836, chapter: '14', type: 'sentence', zh: '老師戴著漂亮的手錶。', ja: ['先生は綺麗な時計をしています', '先生はきれいな時計をしています'] },
  { id: 837, chapter: '14', type: 'sentence', zh: '不太在超市買東西。', ja: ['あまりスーパーで買い物しません'] },
  { id: 838, chapter: '14', type: 'sentence', zh: '不太穿毛衣。', ja: ['あまりセーターを着ません'] },
  { id: 839, chapter: '14', type: 'sentence', zh: '週末不太念書。', ja: ['週末、あまり勉強しません'] },
  { id: 840, chapter: '14', type: 'sentence', zh: '晚上不太吃零食。', ja: ['夜、あまりお菓子を食べません'] },
  { id: 841, chapter: '14', type: 'sentence', zh: '常唱歌。', ja: ['よく歌を歌います'] },
  { id: 842, chapter: '14', type: 'sentence', zh: '不太聽音樂。', ja: ['あまり音楽を聴きません', 'あまり音楽を聞きません'] },
  { id: 843, chapter: '14', type: 'sentence', zh: '高中時，不太去唱卡拉OK。', ja: ['高校の時、あまりカラオケへ行きませんでした'] },
  { id: 844, chapter: '14', type: 'sentence', zh: '以前常寫信。', ja: ['昔、よく手紙を書きました'] },
  { id: 845, chapter: '15', type: 'sentence', zh: '可以關電視。', ja: ['テレビを消してもいいです'] },
  { id: 846, chapter: '15', type: 'sentence', zh: '可以使用這個房間。', ja: ['この部屋を使ってもいいです'] },
  { id: 847, chapter: '15', type: 'sentence', zh: '不好意思，稍微休息一下可以嗎。', ja: ['すみません、ちょっと休んでもいいですか'] },
  { id: 848, chapter: '15', type: 'sentence', zh: '不好意思，提問可以嗎。', ja: ['すみません、質問してもいいですか'] },
  { id: 849, chapter: '15', type: 'sentence', zh: '不可以打開窗戶。', ja: ['窓を開けてはいけません'] },
  { id: 850, chapter: '15', type: 'sentence', zh: '考試時不可以遲到。', ja: ['テストの時、遅刻してはいけません'] },
  { id: 851, chapter: '15', type: 'sentence', zh: '不可以在路上玩。', ja: ['道で遊んではいけません'] },
  { id: 852, chapter: '15', type: 'sentence', zh: '不可以吃點心。', ja: ['お菓子を食べてはいけません'] },
  { id: 853, chapter: '15', type: 'sentence', zh: '可以吃飯。', ja: ['食事してもいいです'] },
  { id: 854, chapter: '15', type: 'sentence', zh: '不可以打電話。', ja: ['電話してはいけません'] },
  { id: 855, chapter: '15', type: 'sentence', zh: '可以抽菸。', ja: ['タバコを吸ってもいいです'] },
  { id: 856, chapter: '15', type: 'sentence', zh: '請說明關於宿舍的生活。', ja: ['寮の生活について、教えてください'] },
  { id: 857, chapter: '15', type: 'sentence', zh: '請說說關於小時候的事。', ja: ['子供の時について、話してください'] },

  // ==================== 附錄專區 (Appendix) ====================
  { id: 901, chapter: 'appendix-others', type: 'vocab', zh: '常常、時常', ja: ['ときどき'] },
  { id: 902, chapter: 'appendix-others', type: 'vocab', zh: '如果', ja: ['もし'] },
  { id: 903, chapter: 'appendix-others', type: 'vocab', zh: '宛如、簡直', ja: ['まるで'] },
  { id: 904, chapter: 'appendix-others', type: 'vocab', zh: '我的、我們的', ja: ['わが'] },
  { id: 905, chapter: 'appendix-others', type: 'vocab', zh: '大的 (連體詞)', ja: ['大きな', 'おおきな'] },
  { id: 906, chapter: 'appendix-others', type: 'vocab', zh: '小的 (連體詞)', ja: ['小さな', 'ちいさな'] },
  { id: 907, chapter: 'appendix-others', type: 'vocab', zh: '可笑的、奇怪的 (連體詞)', ja: ['おかしな'] },
  { id: 908, chapter: 'appendix-others', type: 'vocab', zh: '各式各樣的 (連體詞)', ja: ['いろんな'] },
  { id: 909, chapter: 'appendix-others', type: 'vocab', zh: '了不起的、驚人的', ja: ['たいした'] },
  { id: 910, chapter: 'appendix-others', type: 'vocab', zh: '意想不到的', ja: ['とんだ'] },
  { id: 911, chapter: 'appendix-others', type: 'vocab', zh: '某個', ja: ['ある'] },
  { id: 912, chapter: 'appendix-others', type: 'vocab', zh: '所有、一切', ja: ['あらゆる'] },
  { id: 913, chapter: 'appendix-others', type: 'vocab', zh: '所謂的', ja: ['いわゆる'] },
  { id: 914, chapter: 'appendix-others', type: 'vocab', zh: '然後、而且', ja: ['そして'] },
  { id: 915, chapter: 'appendix-others', type: 'vocab', zh: '因此、所以 (承接上文)', ja: ['それで'] },
  { id: 916, chapter: 'appendix-others', type: 'vocab', zh: '於是、因此', ja: ['そこで'] },
  { id: 917, chapter: 'appendix-others', type: 'vocab', zh: '但是、然而', ja: ['しかし'] },
  { id: 918, chapter: 'appendix-others', type: 'vocab', zh: '但是 (較口語)', ja: ['けれども'] },
  { id: 919, chapter: 'appendix-others', type: 'vocab', zh: '或是、或者', ja: ['あるいは'] },
  { id: 920, chapter: 'appendix-others', type: 'vocab', zh: '喂 (打電話)', ja: ['もしもし'] },
  { id: 921, chapter: 'appendix-others', type: 'vocab', zh: '午安、你好', ja: ['こんにちは'] },
  { id: 922, chapter: 'appendix-others', type: 'vocab', zh: '晚安', ja: ['こんばんは'] },
  { id: 923, chapter: 'appendix-others', type: 'vocab', zh: '再見', ja: ['さようなら'] },
  { id: 924, chapter: 'appendix-others', type: 'vocab', zh: '哎呀、哎喲 (驚訝)', ja: ['あら'] },
  { id: 925, chapter: 'appendix-others', type: 'vocab', zh: '嗯 (肯定)', ja: ['うん'] },
  { id: 930, chapter: 'appendix-pronouns', type: 'vocab', zh: '這裡 (近稱)', ja: ['ここ'] },
  { id: 931, chapter: 'appendix-pronouns', type: 'vocab', zh: '那裡 (中稱)', ja: ['そこ'] },
  { id: 932, chapter: 'appendix-pronouns', type: 'vocab', zh: '那裡 (遠稱)', ja: ['あそこ'] },
  { id: 933, chapter: 'appendix-pronouns', type: 'vocab', zh: '哪裡', ja: ['どこ'] },
  { id: 934, chapter: 'appendix-pronouns', type: 'vocab', zh: '這邊 (近稱/較口語)', ja: ['こっち'] },
  { id: 935, chapter: 'appendix-pronouns', type: 'vocab', zh: '那邊 (中稱/較口語)', ja: ['そっち'] },
  { id: 936, chapter: 'appendix-pronouns', type: 'vocab', zh: '那邊 (遠稱/較口語)', ja: ['あっち'] },
  { id: 937, chapter: 'appendix-pronouns', type: 'vocab', zh: '哪邊 (較口語)', ja: ['どっち'] },
  { id: 938, chapter: 'appendix-pronouns', type: 'vocab', zh: '這邊 / 這位 (近稱/客氣)', ja: ['こちら'] },
  { id: 939, chapter: 'appendix-pronouns', type: 'vocab', zh: '那邊 / 那位 (中稱/客氣)', ja: ['そちら'] },
  { id: 940, chapter: 'appendix-pronouns', type: 'vocab', zh: '那邊 / 那位 (遠稱/客氣)', ja: ['あちら'] },
  { id: 941, chapter: 'appendix-pronouns', type: 'vocab', zh: '哪邊 / 哪位 (客氣)', ja: ['どちら'] },
  { id: 950, chapter: 'appendix-numbers', type: 'vocab', zh: '0', ja: ['0', '零', 'ゼロ', 'れい'] },
  { id: 951, chapter: 'appendix-numbers', type: 'vocab', zh: '100', ja: ['100', '百'] },
  { id: 952, chapter: 'appendix-numbers', type: 'vocab', zh: '300', ja: ['300', '三百'] },
  { id: 953, chapter: 'appendix-numbers', type: 'vocab', zh: '600', ja: ['600', '六百'] },
  { id: 954, chapter: 'appendix-numbers', type: 'vocab', zh: '800', ja: ['800', '八百'] },
  { id: 955, chapter: 'appendix-numbers', type: 'vocab', zh: '1000', ja: ['1000', '千'] },
  { id: 956, chapter: 'appendix-numbers', type: 'vocab', zh: '3000', ja: ['3000', '三千'] },
  { id: 957, chapter: 'appendix-numbers', type: 'vocab', zh: '8000', ja: ['8000', '八千'] },
  { id: 958, chapter: 'appendix-numbers', type: 'vocab', zh: '10000', ja: ['10000', '一万'] },
  { id: 959, chapter: 'appendix-numbers', type: 'vocab', zh: '4點 / 4時', ja: ['4時', '四時'] },
  { id: 960, chapter: 'appendix-numbers', type: 'vocab', zh: '7點 / 7時', ja: ['7時', '七時'] },
  { id: 961, chapter: 'appendix-numbers', type: 'vocab', zh: '9點 / 9時', ja: ['9時', '九時'] },
  { id: 962, chapter: 'appendix-numbers', type: 'vocab', zh: '1分', ja: ['1分', '一分'] },
  { id: 963, chapter: 'appendix-numbers', type: 'vocab', zh: '3分', ja: ['3分', '三分'] },
  { id: 964, chapter: 'appendix-numbers', type: 'vocab', zh: '4分', ja: ['4分', '四分'] },
  { id: 965, chapter: 'appendix-numbers', type: 'vocab', zh: '6分', ja: ['6分', '六分'] },
  { id: 966, chapter: 'appendix-numbers', type: 'vocab', zh: '8分', ja: ['8分', '八分'] },
  { id: 967, chapter: 'appendix-numbers', type: 'vocab', zh: '10分', ja: ['10分', '十分'] },
  { id: 968, chapter: 'appendix-numbers', type: 'vocab', zh: '幾分', ja: ['何分'] },
  { id: 969, chapter: 'appendix-numbers', type: 'vocab', zh: '1日 (一日)', ja: ['1日', '一日'] },
  { id: 970, chapter: 'appendix-numbers', type: 'vocab', zh: '2日 (二日)', ja: ['2日', '二日'] },
  { id: 971, chapter: 'appendix-numbers', type: 'vocab', zh: '3日 (三日)', ja: ['3日', '三日'] },
  { id: 972, chapter: 'appendix-numbers', type: 'vocab', zh: '4日 (四日)', ja: ['4日', '四日'] },
  { id: 973, chapter: 'appendix-numbers', type: 'vocab', zh: '5日 (五日)', ja: ['5日', '五日'] },
  { id: 974, chapter: 'appendix-numbers', type: 'vocab', zh: '6日 (六日)', ja: ['6日', '六日'] },
  { id: 975, chapter: 'appendix-numbers', type: 'vocab', zh: '7日 (七日)', ja: ['7日', '七日'] },
  { id: 976, chapter: 'appendix-numbers', type: 'vocab', zh: '8日 (八日)', ja: ['8日', '八日'] },
  { id: 977, chapter: 'appendix-numbers', type: 'vocab', zh: '9日 (九日)', ja: ['9日', '九日'] },
  { id: 978, chapter: 'appendix-numbers', type: 'vocab', zh: '10日 (十日)', ja: ['10日', '十日'] },
  { id: 979, chapter: 'appendix-numbers', type: 'vocab', zh: '14日 (十四日)', ja: ['14日', '十四日'] },
  { id: 980, chapter: 'appendix-numbers', type: 'vocab', zh: '20日 (二十日)', ja: ['20日', '二十日'] },
  { id: 981, chapter: 'appendix-numbers', type: 'vocab', zh: '24日 (二十四日)', ja: ['24日', '二十四日'] },
  { id: 982, chapter: 'appendix-numbers', type: 'vocab', zh: '幾號 / 幾日', ja: ['何日'] },
  { id: 983, chapter: 'appendix-numbers', type: 'vocab', zh: '1人 (一人)', ja: ['1人', '一人'] },
  { id: 984, chapter: 'appendix-numbers', type: 'vocab', zh: '2人 (二人)', ja: ['2人', '二人'] },
  { id: 985, chapter: 'appendix-numbers', type: 'vocab', zh: '4人 (四人)', ja: ['4人', '四人'] },
  { id: 986, chapter: 'appendix-numbers', type: 'vocab', zh: '1個 (一個)', ja: ['1個', '一個'] },
  { id: 987, chapter: 'appendix-numbers', type: 'vocab', zh: '6個 (六個)', ja: ['6個', '六個'] },
  { id: 988, chapter: 'appendix-numbers', type: 'vocab', zh: '8個 (八個)', ja: ['8個', '八個'] },
  { id: 989, chapter: 'appendix-numbers', type: 'vocab', zh: '10個 (十個)', ja: ['10個', '十個'] },
  { id: 990, chapter: 'appendix-numbers', type: 'vocab', zh: '幾個', ja: ['何個', 'いくつ'] },
  { id: 991, chapter: 'appendix-numbers', type: 'vocab', zh: '1本 (細長物)', ja: ['1本', '一本'] },
  { id: 992, chapter: 'appendix-numbers', type: 'vocab', zh: '3本 (細長物)', ja: ['3本', '三本'] },
  { id: 993, chapter: 'appendix-numbers', type: 'vocab', zh: '6本 (細長物)', ja: ['6本', '六本'] },
  { id: 994, chapter: 'appendix-numbers', type: 'vocab', zh: '8本 (細長物)', ja: ['8本', '八本'] },
  { id: 995, chapter: 'appendix-numbers', type: 'vocab', zh: '10本 (細長物)', ja: ['10本', '十本'] },
  { id: 996, chapter: 'appendix-numbers', type: 'vocab', zh: '幾本', ja: ['何本'] },
  { id: 997, chapter: 'appendix-numbers', type: 'vocab', zh: '1冊', ja: ['1冊', '一冊'] },
  { id: 998, chapter: 'appendix-numbers', type: 'vocab', zh: '8冊', ja: ['8冊', '八冊'] },
  { id: 999, chapter: 'appendix-numbers', type: 'vocab', zh: '10冊', ja: ['10冊', '十冊'] },
  { id: 1000, chapter: 'appendix-numbers', type: 'vocab', zh: '1回 (一次)', ja: ['1回', '一回'] },
  { id: 1001, chapter: 'appendix-numbers', type: 'vocab', zh: '6回 (六次)', ja: ['6回', '六回'] },
  { id: 1002, chapter: 'appendix-numbers', type: 'vocab', zh: '8回 (八次)', ja: ['8回', '八回'] },
  { id: 1003, chapter: 'appendix-numbers', type: 'vocab', zh: '10回 (十次)', ja: ['10回', '十回'] },
  { id: 1004, chapter: 'appendix-numbers', type: 'vocab', zh: '1階 (一樓)', ja: ['1階', '一階'] },
  { id: 1005, chapter: 'appendix-numbers', type: 'vocab', zh: '3階 (三樓)', ja: ['3階', '三階'] },
  { id: 1006, chapter: 'appendix-numbers', type: 'vocab', zh: '6階 (六樓)', ja: ['6階', '六階'] },
  { id: 1007, chapter: 'appendix-numbers', type: 'vocab', zh: '8階 (八樓)', ja: ['8階', '八階'] },
  { id: 1008, chapter: 'appendix-numbers', type: 'vocab', zh: '10階 (十樓)', ja: ['10階', '十階'] },
  { id: 1009, chapter: 'appendix-numbers', type: 'vocab', zh: '幾樓', ja: ['何階'] },
  { id: 1020, chapter: 'appendix-names', type: 'vocab', zh: '陳 (姓氏)', ja: ['陳'] },
  { id: 1021, chapter: 'appendix-names', type: 'vocab', zh: '林 (姓氏)', ja: ['林'] },
  { id: 1022, chapter: 'appendix-names', type: 'vocab', zh: '黃 / 洪 (姓氏)', ja: ['黄', '洪'] },
  { id: 1023, chapter: 'appendix-names', type: 'vocab', zh: '張 (姓氏)', ja: ['張'] },
  { id: 1024, chapter: 'appendix-names', type: 'vocab', zh: '李 (姓氏)', ja: ['李'] },
  { id: 1025, chapter: 'appendix-names', type: 'vocab', zh: '王 (姓氏)', ja: ['王'] },
  { id: 1026, chapter: 'appendix-names', type: 'vocab', zh: '吳 (姓氏)', ja: ['呉'] },
  { id: 1027, chapter: 'appendix-names', type: 'vocab', zh: '劉 (姓氏)', ja: ['劉'] },
  { id: 1028, chapter: 'appendix-names', type: 'vocab', zh: '蔡 (姓氏)', ja: ['蔡'] },
  { id: 1029, chapter: 'appendix-names', type: 'vocab', zh: '楊 / 葉 (姓氏)', ja: ['楊', '葉'] },
  { id: 1030, chapter: 'appendix-names', type: 'vocab', zh: '許 (姓氏)', ja: ['許'] },
  { id: 1031, chapter: 'appendix-names', type: 'vocab', zh: '鄭 (姓氏)', ja: ['鄭'] },
  { id: 1032, chapter: 'appendix-names', type: 'vocab', zh: '謝 (姓氏)', ja: ['謝'] },
  { id: 1033, chapter: 'appendix-names', type: 'vocab', zh: '郭 (姓氏)', ja: ['郭'] },
  { id: 1034, chapter: 'appendix-names', type: 'vocab', zh: '邱 (姓氏)', ja: ['邱'] },
  { id: 1035, chapter: 'appendix-names', type: 'vocab', zh: '曾 (姓氏)', ja: ['曾'] },
  { id: 1036, chapter: 'appendix-names', type: 'vocab', zh: '廖 (姓氏)', ja: ['廖'] },
  { id: 1037, chapter: 'appendix-names', type: 'vocab', zh: '賴 (姓氏)', ja: ['頼'] },
  { id: 1038, chapter: 'appendix-names', type: 'vocab', zh: '徐 (姓氏)', ja: ['徐'] },
  { id: 1039, chapter: 'appendix-names', type: 'vocab', zh: '周 (姓氏)', ja: ['周'] },
  { id: 1050, chapter: 'appendix-family', type: 'vocab', zh: '祖父 / 外公 (自稱)', ja: ['祖父'] },
  { id: 1051, chapter: 'appendix-family', type: 'vocab', zh: '爺爺 / 外公 (他稱)', ja: ['お爺さん'] },
  { id: 1052, chapter: 'appendix-family', type: 'vocab', zh: '祖母 / 外婆 (自稱)', ja: ['祖母'] },
  { id: 1053, chapter: 'appendix-family', type: 'vocab', zh: '奶奶 / 外婆 (他稱)', ja: ['お婆さん'] },
  { id: 1054, chapter: 'appendix-family', type: 'vocab', zh: '父親 (自稱)', ja: ['父'] },
  { id: 1055, chapter: 'appendix-family', type: 'vocab', zh: '爸爸 (他稱/敬稱)', ja: ['お父さん'] },
  { id: 1056, chapter: 'appendix-family', type: 'vocab', zh: '母親 (自稱)', ja: ['母'] },
  { id: 1057, chapter: 'appendix-family', type: 'vocab', zh: '媽媽 (他稱/敬稱)', ja: ['お母さん'] },
  { id: 1058, chapter: 'appendix-family', type: 'vocab', zh: '哥哥 (自稱)', ja: ['兄'] },
  { id: 1059, chapter: 'appendix-family', type: 'vocab', zh: '哥哥 (他稱/敬稱)', ja: ['お兄さん'] },
  { id: 1060, chapter: 'appendix-family', type: 'vocab', zh: '姊姊 (自稱)', ja: ['姉'] },
  { id: 1061, chapter: 'appendix-family', type: 'vocab', zh: '姊姊 (他稱/敬稱)', ja: ['お姉さん'] },
  { id: 1062, chapter: 'appendix-family', type: 'vocab', zh: '弟弟 (自稱)', ja: ['弟'] },
  { id: 1063, chapter: 'appendix-family', type: 'vocab', zh: '弟弟 (他稱)', ja: ['弟さん'] },
  { id: 1064, chapter: 'appendix-family', type: 'vocab', zh: '妹妹 (自稱)', ja: ['妹'] },
  { id: 1065, chapter: 'appendix-family', type: 'vocab', zh: '妹妹 (他稱)', ja: ['妹さん'] },
  { id: 1066, chapter: 'appendix-family', type: 'vocab', zh: '兒子 (自稱)', ja: ['息子'] },
  { id: 1067, chapter: 'appendix-family', type: 'vocab', zh: '女兒 (自稱)', ja: ['娘'] },
  { id: 1068, chapter: 'appendix-family', type: 'vocab', zh: '別人家女兒 (他稱)', ja: ['お嬢さん'] }
];

const CHAPTERS = [
  { id: 'all', name: '全範圍綜合' },
  { id: '1', name: '第1課　私は　張です。' },
  { id: '2', name: '第2課　あれは　我的傘です。' },
  { id: '3', name: '第3課　これは　ちょっと　高いですね。' },
  { id: '4', name: '第4課　納豆が　苦手です。' },
  { id: '5', name: '第5課　料理も　おいしかったです。' },
  { id: '6', name: '第6課　バス停は　どこに　ありますか。' },
  { id: '7', name: '第7課　かばんの中に　何が　ありますか。' },
  { id: '8', name: '第8課　いつも　どこで　買い物しますか。' },
  { id: '9', name: '第9課　夕べ　寝ませんでした。' },
  { id: '10', name: '第10課　試験は　8時からです。' },
  { id: '11', name: '第11課　土曜日の　午後、空港へ　行きます。' },
  { id: '12', name: '第12課　今日は、スパゲッティを　食べたいです。' },
  { id: '13', name: '第13課　ここに　お名前を　書いて　ください。' },
  { id: '14', name: '第14課　ニューヨークの　大學で　芸術を　勉強して　います。' },
  { id: '15', name: '第15課　道で　遊んでは　いけません。' },
  { id: 'divider', name: '~~~~~~ 附錄專區 ~~~~~~' },
  { id: 'appendix-others', name: '附錄：其他常用詞彙 (品詞)' },
  { id: 'appendix-pronouns', name: '附錄：指示代名詞' },
  { id: 'appendix-numbers', name: '附錄：數字、時間與量詞' },
  { id: 'appendix-names', name: '附錄：臺灣常見姓氏' },
  { id: 'appendix-family', name: '附錄：家人稱謂' }
];

const PRACTICE_TYPES = [
  { id: 'all', name: '全部混合' },
  { id: 'vocab', name: '單字 (平假名/漢字)' },
  { id: 'katakana', name: '外來語 (片假名)' },
  { id: 'grammar', name: '文法應用' },
  { id: 'sentence', name: '句型翻譯' }
];

const API_MODELS = {
  text: [
    { id: 'gemini-3.1-flash-lite', label: 'Gemini 3.1 Flash Lite', limitStr: '500 次/天' },
    { id: 'gemini-2.5-flash-preview-09-2025', label: 'Gemini 2.5 Flash', limitStr: '20 次/天' },
    { id: 'gemini-3.5-flash', label: 'Gemini 3.5 Flash', limitStr: '20 次/天' }
  ],
  tts: [
    { id: 'gemini-3.1-flash-tts', label: 'Gemini 3.1 Flash TTS', limitStr: '10 次/天' },
    { id: 'gemini-2.5-flash-preview-tts', label: 'Gemini 2.5 Flash TTS', limitStr: '10 次/天' }
  ]
};

export { KANJI_DICT, KANJI_KEYS, KANJI_REGEX, QUIZ_DATA, CHAPTERS, PRACTICE_TYPES, API_MODELS };